### ISSUE TITLE
CaptureOrderResult.Success is lacking payment information

### ISSUE THREAD

**Issue by mikasR** [paypal/android-checkout-sdk#10]
Hi @CodyEngel ,

We have implemented refunds with the PHP SDK, and for that we need the paymentID or captureID (i don´t know).

On iOS we get this value on the success response of the capture method. However, in android we only get an orderStatus which is an enum and an ID which is the orderID and is no good for us to call the refund method.

Could you please implemente on the android SDK the same information that we get on the iOS SDK?

**Comment by CodyEngel** [comment]
Hey @mikasR -- thanks for the request. I added this to our backlog, we should be able to start work on it soon. I'll update this ticket once it's ready to go.

**Comment by mikasR** [comment]
Hi @CodyEngel,

Thank you for the feedback.
We really need this feature so we can launch our app to production.

Thanks

**Comment by CodyEngel** [comment]
We've added `purchaseUnits` to the Success result for both Authorize and Capture actions. The `PurchaseUnit` object will now contain the capture and authorize IDs which can be used to help facilitate returns. This change is expected to be available in our next regular release.

**Comment by tdchow** [comment]
Hey @mikasR. The 0.4.0 release is out! This release added the additional data in the `OnApprove` callback.

```
implementation 'com.paypal.checkout:android-sdk:0.4.0'
```
