### ISSUE TITLE
Shipping address validation on Paysheet starts

### ISSUE THREAD

**Issue by mauro-poq** [paypal/android-checkout-sdk#100]
I have a case where the user has only invalid addresses in PayPal when I start the Paysheet, in my case the user has only UK addresses and the company accepts only US addresses for delivery. So when the user opens the Paysheet we have already a default address set by PayPal SDK but the `onShippingChange` is not called, so I'm not able to call my BackEnd to verify.
Talking to the iOS developer, he said to me that every time he opens the paysheet the `onShippingChange` is invoked and he is able to validate the address.
I don't know if this is a bug or not, however, is there a way to make the SDK invoke `onShippingChange` as soon as the user opens the paysheet, maybe some configuration?
Other scenarios are working fine, if the user changes the address I receive the callback and I'm able to validate the address.

**Comment by tdchow** [comment]
Hi @mauro-poq - Sorry for the delay. We should be invoking the `OnShippingChange` callback when the paysheet loads. 

We've picked up the work and the change should be in the next release of the SDK. Will keep you updated!

**Comment by mauro-poq** [comment]
Hey @tdchow how are you?
Back in this item, in the latest version (0.8.7) I can see that when we first launch the paysheet the `onShippingChange` is invoked and that address is cached, however, when the user finishes the first purchase and execute a second purchase the address is cached and the SDK is not invoking `onShippingChange`, this is bringing me some problems because I need the address to calculate the Taxes.

**Questions:** 
- Is there a plan for the next releases to start executing the `onShippingChange` callback (if it makes sense) every time the paysheet is open, even if the address is cached?
- If not (or as a temporary workaround), is there a way to clear the cache and force this behaviour?

**Note:** 
Testing here I see that if I close the app and open it again the `onShippingChange` callback is executed, which makes me think that there is a cache.

**Comment by tdchow** [comment]
hi @mauro-poq! Apologies for not getting back to you here!

I was able to verify that the second time the SDK is invoked, the `onShippingChange` callback is not called 😕

Thanks for calling this bug out. I've created a ticket for the team to resolve this. We'll keep you updated on the fix here.

**Comment by mauro-poq** [comment]
Hey, @chpypl I have just tested it on version 0.8.8 and the behaviour looks the same as described above, is the fix already in or it will be in the next version?

**Comment by chpypl** [comment]
Hi @mauro-poq the fix will be in the next version

**Comment by mauro-poq** [comment]
Hi @tdchow and @chpypl, I have tested this in the new version (0.112.0) to see if the change were included, however, I can see now that the `onShippingChange` method receives an object called `ShippingChangeAddress` which does not include the fields `addressLine1` and `addressLine2` as the former Address object, in this case, how do we get the street name?
I have not tested the problem yet as this break my use case, so I can't go forward.

**Comment by tdchow** [comment]
Hi @mauro-poq - sorry for the delayed response.

The removal of `addressLine1` and `addressLine2` was an intentional change due to a privacy concern. Are you able to calculate shipping costs based on the buyer's selected city, state, and postal code?

**Comment by mauro-poq** [comment]
Hey @tdchow - no problem man!

I see, I think it will not be a problem, but before checking with the BE team, can you confirm if the fields will be present when the user places the order (press the pay button)?

**Comment by tdchow** [comment]
The OnShippingChange callback should be called initially when the paysheet is loaded and whenever the buyer changes their shipping address - both of which should be before the user clicks on the CTA button. If you're seeing different behavior please let me know and we can further investigate!

**Comment by tdchow** [comment]
@mauro-poq - Awesome, thanks so much for retesting and following up here. Will close out this issue.
