### ISSUE TITLE
online crash caused by paypal sdk 

### ISSUE THREAD

**Issue by HuixingWong** [paypal/android-checkout-sdk#104]
Before you create a new issue, please search for similar issues. It's possible somebody has encountered this bug already. **PLEASE REMOVE THIS LINE TO ACKNOWLEDGE THAT AN ISSUE DOESN'T ALREADY EXIST FOR THIS BUG**

**Describe the bug**

`Fatal Exception: java.util.NoSuchElementException
Collection contains no element matching the predicate.
com.paypal.pyplcheckout.addshipping.AddressAutoCompleteViewModel.getCountryPositionOnList (AddressAutoCompleteViewModel.kt:370)
com.paypal.pyplcheckout.addressbook.view.customviews.PayPalNewShippingAddressSearchView.initViews (PayPalNewShippingAddressSearchView.kt:156)
com.paypal.pyplcheckout.addressbook.view.customviews.PayPalNewShippingAddressSearchView.access$initViews (PayPalNewShippingAddressSearchView.kt:62)
com.paypal.pyplcheckout.addressbook.view.customviews.PayPalNewShippingAddressSearchView$initViews$1.onTouch (PayPalNewShippingAddressSearchView.kt:141)`

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Android Version: [e.g. API 30]
 - Device: [e.g. Emulator or One Plus 9]
 - Browser [e.g. chrome, safari] <- only applicable for app switches or fallback situations
 - SDK Version [e.g. 0.1.0]

**Additional context**

**Comment by saperi22** [comment]
Hi @HuixingWong, please provide detailed steps to reproduce the error.

Also, please fill in the details to better assist us finding and fixing the bug you are seeing.

**Comment by HuixingWong** [comment]
sdk version :  0.6.0

device :  Galaxy A52s 5G 

Os version : android 12

I can't reproduce this because this is a crash report by firebase.

By the way, all of the crashes in our app now come from the paypal SDK.
<img width="581" alt="截屏2022-05-04 09 43 55" src="https://user-images.githubusercontent.com/15938606/166612956-bdceedca-9986-470f-acbd-168d9e5dbdfc.png">

this is one more new crash form PayPal sdk.

maybe you guys should test on more device and system versions device before release the sdk

**Comment by sterlingann** [comment]
@saperi22  Do you mind following up on this one please?

**Comment by saperi22** [comment]
@HuixingWong we'll be looking at these issues in the coming days. I'll provide you with an update once they are identified and fixed.

**Comment by HuixingWong** [comment]
Thanks.  By the way, is Paypal hiring?  Our company is closed  last month 😂

**Comment by saperi22** [comment]
@HuixingWong You can find the current job openings at [https://careers.pypl.com/home/default.aspx](https://careers.pypl.com/home/default.aspx)
You should be able to search for jobs based on your career aspirations and location preferences.

**Comment by HuixingWong** [comment]
@saperi22  Thanks again ！

**Comment by saperi22** [comment]
A fix for `NoSuchElementException` was merged in today. It missed to make it to the immediate next release, however, it should be included in the following release.
Thanks for reporting the error.

**Comment by HuixingWong** [comment]
> 
Hello is this fix released ?

**Comment by saperi22** [comment]
@HuixingWong no, the fix has not been released yet.
I'll provide you with an update once I know more about when it is going to make it to a release.

**Comment by saperi22** [comment]
This should be now fixed in https://github.com/paypal/android-checkout-sdk/releases/tag/v0.112.0.

I'll close this ticket. Please open a new ticket if you see other issues.
