### ISSUE TITLE
Failed to initialize button PayLaterButton and PayPalCreditButton

### ISSUE THREAD

**Issue by longnguyencmg** [paypal/android-checkout-sdk#11]
When I tried to setup buttons, after loading a while I can only see the button `PayPalButton`. Two other buttons (`PayLaterButton`, `PayPalCreditButton`) were disappeared. 

I'm sure what's wrong with my config.

Please help with this issue

**Comment by CodyEngel** [comment]
Hey @longnguyencmg -- for Payment Buttons they will run through a funding eligibility check, if that funding option is not eligible then the button will not be rendered. `PayPalButton` will generally always be eligible so it's recommended to make use of that as a fallback if the preferred button is not eligible.
