### ISSUE TITLE
He approves the payment and activates the premium in the app but does not charge the customer

### ISSUE THREAD

**Issue by guilindohick** [paypal/android-checkout-sdk#110]
Before you create a new issue, please search for similar issues. It's possible somebody has encountered this bug already. **PLEASE REMOVE THIS LINE TO ACKNOWLEDGE THAT AN ISSUE DOESN'T ALREADY EXIST FOR THIS BUG**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Android Version: [e.g. API 30]
 - Device: [e.g. Emulator or One Plus 9]
 - Browser [e.g. chrome, safari] <- only applicable for app switches or fallback situations
 - SDK Version [e.g. 0.6.2]

**Additional context**

**Comment by ChrisGuzman** [comment]
@guilindohick Please provide steps to reproduce the bug.
Also, please fill in the requested information (SDK version, Device, OS version, etc.). Thank you!

**Comment by guilindohick** [comment]
@ChrisGuzman It doesn't show any error or bug message, the whole process works fine, it just doesn't charge the paypal account.

**Comment by ChrisGuzman** [comment]
Thanks @guilindohick. Please fill in the requested information in the issue description (SDK version, Device, OS version, etc.) so I can further investigate.

**Comment by guilindohick** [comment]
'com.paypal.checkout:android-sdk:0.6.2'
Galaxy S10 Android 10

**Comment by guilindohick** [comment]
@ChrisGuzman PaymentPaypal: CaptureOrderResult: Error(message=Capture order failed., reason=Capture order response was not successful. Response status code: 422)

When I click on Pay Now in Paypal it appears in the logcat

**Comment by ChrisGuzman** [comment]
@guilindohick please edit the issue and add steps to reproduce the behavior in the **To Reproduce** section and add screenshots to help explain your problem in the ** Screenshots** section. Additionally, can you tell us if you are creating the Order via the SDK or if the order is created server side. We'd also like for you to share the package name of the app you're experiencing this error. It's difficult to diagnose the issue without these details. Thank you very much.

**Comment by ChrisGuzman** [comment]
@guilindohick 
Before going live, PayPal must review your app to approve the sharing of customer data. The review automatically starts once you select the Log in with PayPal checkbox on your Developer Dashboard (Step 3 of [Enable the SDK](https://developer.paypal.com/limited-release/native-checkout/android/#enable-the-sdk)). The review for sandbox apps typically completes within 2 hours. The review for live apps typically completes within 2 business days, but under certain circumstance, can take up to 10 business days.

This may be the reason for your error. Can you verify that you have completed that step and completely read through the [developer documentation](https://developer.paypal.com/limited-release/native-checkout/android/)
