### ISSUE TITLE
App does not open after logging into PayPal

### ISSUE THREAD

**Issue by Mad-Bones** [paypal/android-checkout-sdk#111]
**Describe the bug**
After logging into a PayPal sandbox account, browsers display an error: No application associated with the "com.myApp:" protocol was found on your system.

**To Reproduce**
1. Click on 'PayPal button'
2. Login account 
3. See error

**Expected behavior**
loggin in the sandbox account and continue with the purchase
  
**Smartphone (please complete the following information):**
 - Minimun Android Version: [API 23]
 - Android Version: [API 30]
 - Minimun android 
 - Device: [Emulator and physical phone]
 - Browser [chrome, opera,ucBrowser, edge]
 - SDK Version [0.6.0, 0.6.1, 0.6.2]

**Additional context**
A week ago it worked correctly, the app contains the same name of the package, THERE WERE NO CHANGES IN THE SANDBOX. When I upgraded the sdk to 0.6.2 the problem started, I went back to 0.6.0 (as it was originally) and the problem persists.

**Comment by Mad-Bones** [comment]
7 days... no answer...

**Comment by ctamura** [comment]
I'm trying to reproduce your issue now. I will keep you updated on any progress.

**Comment by tdchow** [comment]
Hey @Mad-Bones - as we're looking into the issue would you be able to provide a screenshot of the webpage that contains the error?

Could you also share your ClientID and a code snippet of setting your `CheckoutConfig`?

**Comment by Mad-Bones** [comment]
`
    PayPalButton payPalButton;

@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
[...]

        payPalButton = findViewById(R.id.payPalButton);
CheckoutConfig config = new CheckoutConfig(
                this.getApplication(),
                PAYPAL_CLIENT_ID,
                Environment.SANDBOX,
                BuildConfig.APPLICATION_ID + "://paypalpay",
                CurrencyCode.EUR,
                UserAction.PAY_NOW,
                null,
                new SettingsConfig(
                        true,
                        false
                )
        );
        PayPalCheckout.setConfig(config);

payPalButton.setup(
                (CreateOrder) createOrderActions -> {
                    purchaseUnits = new ArrayList<>();
                    purchaseUnits.add(
                            new PurchaseUnit.Builder()
                                    .amount(
                                            new Amount.Builder()
                                                    .currencyCode(CurrencyCode.EUR)
                                                    .value("2.00")
                                                    .build()
                                    )
                                    .build()
                    );
                    Order order = new Order(
                            OrderIntent.CAPTURE,
                            new AppContext.Builder()
                                    .userAction(UserAction.PAY_NOW)
                                    .build(),
                            purchaseUnits,
                            null
                    );
                    createOrderActions.create(order, (CreateOrderActions.OnOrderCreated) null);
                },
                (OnApprove) approval -> approval.getOrderActions().capture(result -> {

                    Intent intent = new Intent(MainActivity.this, PagoExitoso.class);
                    startActivity(intent);
                    finish();
                    Log.i("CaptureOrder", String.format("CaptureOrderResult: %s", result));
                })
        );
}
`

screenshot
![Screenshot_20220519-133822](https://user-images.githubusercontent.com/57918059/170558706-0131cdf9-6cf8-4e5d-9da9-b1f2142c9e09.png)

**Comment by tdchow** [comment]
@Mad-Bones Hmm when the auth webpage is loaded, is it opening in a Chrome Custom Tab, or is it opening in your browser app? the screenshot is looking a little strange, as the SDK shouldn't be opening anything in the external browser. 

Few follow up questions:
- Which browser do you have installed on this device?
- Could you share a screen recording from pressing the payment button all the way until this error webview is loaded?

**Comment by Mad-Bones** [comment]
How is it possible that when calling the PayPal helpline, they inform me that I cannot use a webview in my app to use the api, and you ask me if I use an external browser has? It has no consistency. Anyway, I can not provide more data since I deleted the api and we changed to another api that had no fault, goodbye
