### ISSUE TITLE
 [Java][0.6.2]cancel callback is not called ()->{}

### ISSUE THREAD

**Issue by santhoshnarendra** [paypal/android-checkout-sdk#112]
The issue was not found by me in existing columns, so have created a new one here.
**When User cancels the paypal checkout, callback errorInfo is executed in the place of cancel**

- create order is executed as expected from `paypalCheckout.startCheckout`
- when user proceeds with the order, order is placed successfully from `paypalCheckout.registerCallbacks( approval -> {} )`
- when user intentionally cancels the order, order is cancelled but the block executed is `errorInfo` instead of `cancel`

**Expected behavior**
cancel callback block should be executed

Update

Issue seems to be with returnUrl, but I am able to get returnUrl here

`{ NativeMap: {"live":false,"returnUrl":"appid://paypalpay","clientId":"clientId"} }`

Error

`ErrorInfo(error=java.lang.IllegalArgumentException: Return URL is null, reason=Error approving order, correlationIds=CorrelationIds(eligibilityDebugID=2a51fca0caa26, fundingEligibilityDebugID=null, updateClientConfigDebugID=31453bc782837, lsatUpgradeDebugID=null, fetchPayloadDebugID=77c3992bb3592, currencyConversionDebugID=null, finishCheckoutDebugID=null), orderId=1RK16221DT285234M, nativeSdkVersion=1.9.9)`

**Smartphone:**
 - Android Version: 11
 - Device: Samsung Galaxy M51
 - SDK Version 0.6.2
 - ReactNative Module used

**Comment by tdchow** [comment]
Hi @santhoshnarendra - Would you be able to provide a screen recording of the cancel flow where you're seeing the onError callback invoked?

Are you seeing the native checkout experience or are you seeing a full screen webview loaded?

**Comment by tdchow** [comment]
@santhoshnarendra - thanks so much for the screen recording! We'll take a look at this internally. Thanks again for reporting!

**Comment by ctamura** [comment]
@santhoshnarendra What ReactNative module are you referring to in your original post?

**Comment by ctamura** [comment]
@santhoshnarendra Are you modifying the OnCancel, OnError callbacks or using a custom return URL?

**Comment by santhoshnarendra** [comment]
@ctamura  thanks a lot for your reply, I will shortly send you the block of Code for Config. I believe the returnUrl works well, as if it doesn't we wont be navigated back though the onError Block works. 

We have modified a bit of onCancel, onError and approve callbacks but all those are based on the docs. The issue we face mainly is that, onCancel (Which supposed to be triggered when user cancels the checkout, but instead onError is triggered)

**Comment by santhoshnarendra** [comment]
Action Block Code

```
PayPalCheckout.registerCallbacks(
                approval -> {
                    WritableMap map = Arguments.createMap();
                    map.putBoolean("success", true);
                    promise.resolve(map);
                },
                null,
                () -> {
                    // Block which is not executed
                    WritableMap error = Arguments.createMap();
                    WritableMap map = Arguments.createMap();
                    error.putString("problem", "USER_CANCELED");
                    map.putBoolean("success", false);
                    map.putMap("error", error);
                    promise.resolve(map);
                },
                errorInfo -> {
                    // Block which is executed always
                    WritableMap error = Arguments.createMap();
                    WritableMap map = Arguments.createMap();
                    error.putString("problem", "PAYMENT_ERROR");
                    error.putString("reason", errorInfo.getReason());
                    error.putString("error", String.valueOf(errorInfo.getError()));
                    map.putBoolean("success", false);
                    map.putMap("error", error);
                    promise.resolve(map);
                }
        );

**Comment by santhoshnarendra** [comment]
@ctamura @tdchow  Kindly find the Code Snippet above, thanks!

**Comment by GraceHuntley** [comment]
Hi @santhoshnarendra sorry about the delayed response I have been in the process of debugging this issue. I am happy to announce that I have found the source of the issue and I am in the process of testing the solution. We will update you when we have a release with the fix. Thank you for your detailed bug report.

**Comment by santhoshnarendra** [comment]
Hi @GraceHuntley , thanks for the update. Looking forward to the fix!

**Comment by tdchow** [comment]
hi @santhoshnarendra - this issue should now be resolved in the latest version of the SDK. Please try using version 0.8.0. Going to close this issue for now, but if you're still seeing unexpected behavior with the callback, please reply here!
