### ISSUE TITLE
error when click on checkout

### ISSUE THREAD

**Issue by ibrelm** [paypal/android-checkout-sdk#114]
this screen showing when click on checkout button, it must open login page for paypal , please fix this urgently, note : i add correct client id and code is clean thanks, pls see picture error 
![Screenshot_2022-06-03-03-13-23](https://user-images.githubusercontent.com/27866362/171773771-de8a78e1-bf11-49e1-8399-32f15d06cf5a.png)

**Comment by ibrelm** [comment]
> i have same problem, but with live environment. In sandbox there is no issue

thanks bro

**Comment by tdchow** [comment]
Hey @ibrelm - would you be able to provide me the client ID you're passing into the SDK? 

@sanjivdhakal - Will respond to your issue shortly!

**Comment by winzoor** [comment]
I have same problem, but with sandbox enviroment.
I am use SDK "android-sdk:0.6.0"

Client ID:
ATc1nb1_zQ1bvW6h_oAJppkSnjVRUm6hV3dtS53QNorq1ik4CjgimugD4MnxgAK3C3sqrIrCG2yTXTc9

**Comment by tdchow** [comment]
Hey @winzoor - can you log into the PayPal developer portal, navigate to your REST app, and ensure that `Native Checkout SDK` is enabled? There was a bug on the portal where this option was hidden.

<img width="572" alt="image001" src="https://user-images.githubusercontent.com/5005216/174832457-68b17811-3731-4f34-a24a-5b7edfa74436.png">

If you're still having issues, can you please open a new GitHub issue?

**Comment by winzoor** [comment]
I already checked the portal and I already saw the option to enable the native checkout payment.
Thanks.
________________________________
De: Tim Chow ***@***.***>
Enviado: martes, 21 de junio de 2022 10:01 a. m.
Para: paypal/android-checkout-sdk ***@***.***>
CC: winzoor ***@***.***>; Mention ***@***.***>
Asunto: Re: [paypal/android-checkout-sdk] error when click on checkout (Issue #114)


Hey @winzoor<https://github.com/winzoor> - can you log into the PayPal developer portal, navigate to your REST app, and ensure that Native Checkout SDK is enabled? There was a bug on the portal where this option was hidden.

[image001]<https://user-images.githubusercontent.com/5005216/174832457-68b17811-3731-4f34-a24a-5b7edfa74436.png>

If you're still having issues, can you please open a new GitHub issue?

**Comment by GengJian** [comment]
Unfortunately, I also encountered the same problem, but I couldn't find the switch of "enable the Native Checkout SDK"

**Comment by ChrisGuzman** [comment]
@GengJian could you show me a screenshot of the REST app options in your developer portal? It should look similar to this. This will help me determine if the bug where the `Native Checkout SDK` option is hidden still exists.

![image](https://user-images.githubusercontent.com/1993855/176930001-ae7c121b-25e0-45a2-8036-5a1779d5b16d.png)

**Comment by ibrelm** [comment]
i don't have this option for native checkout SDK on my developer portal 
![Uploading Capture d’écran 2022-07-01 172154.png…]()

**Comment by MAtech1850** [comment]
I have an app that uses its services to sell products from within the app to users but every time a user tries to purchase a product, it says "vendor account doesnt have a verified email address paypal" any solution please?
