### ISSUE TITLE
Invalid Scope error on Live Environment

### ISSUE THREAD

**Issue by sanjivdhakal** [paypal/android-checkout-sdk#115]
I implement this sdk on my android application for payment button, all was success on sandbox but when i switch to live environment, after calling create order, the new tab shows invalid scope. What may be the problem? Scopes (Fullname, email, paypalid...) are already verified by paypal.

**Comment by blob810** [comment]
I have the exact same problem. We have a Business Account. Native Checkout on Android is working in the sandbox. But in live environment I get the same problem - invalid scope. The configuration of the app in the developer account is identical with the configuration of the sandbox app.

**Comment by sanjivdhakal** [comment]
> I have the exact same problem. We have a Business Account. Native Checkout on Android is working in the sandbox. But in live environment I get the same problem - invalid scope. The configuration of the app in the developer account is identical with the configuration of the sandbox app.

Please Share if you found any solution

**Comment by blob810** [comment]
@tdchow 
Do you have an idea how to solve the problem. In the developer dashboard sign in with PayPal is activated. Thank you.

**Comment by tdchow** [comment]
Hey @sanjivdhakal and @blob810 - would you both be able to provide me with your live client ID? I'll do some digging on my end to see what scope issues you both have. Thanks!

**Comment by blob810** [comment]
Thanks for your fast reply. Here is my client id for this application. 

`AeFwbik8V07ENCFHlWxD-4nP4zor72XqAb2YoTbhPvh7do6zBTygsQtEMJ2ilhybn_9nIxREjM61C0kb`

**Comment by sanjivdhakal** [comment]
And here is mine AeyJxIfc52ZFDyEysKR32yxoGcm5aFMFFPN1CJewOdKiwgnXk0_fyWz4P5GpYSfJsnq-DqotpOJ21pGu

**Comment by sanjivdhakal** [comment]
@tdchow Any Updates?

**Comment by tdchow** [comment]
@sanjivdhakal - No updates to share yet. I'm still following up with an internal team to add the correct scope to your client ID.

**Comment by blob810** [comment]
Hi @tdchow,
it's working now in the live environment. I'm very happy. Thanks for your help.

**Comment by sanjivdhakal** [comment]
Solved, Thanks
