### ISSUE TITLE
Paypal working in sandbox but not in live

### ISSUE THREAD

**Issue by MilanGhimire666** [paypal/android-checkout-sdk#116]
Recently I integrated PayPal in my application . Everything works fine in sandbox but i got **( Invalid Scope )** error in my Live environment.

Can you please help me ?

**Comment by tdchow** [comment]
Hi @MilanGhimire666 - would you be able to provide me with your Live client ID?

**Comment by MilanGhimire666** [comment]
AeyJxIfc52ZFDyEysKR32yxoGcm5aFMFFPN1CJewOdKiwgnXk0_fyWz4P5GpYSfJsnq-DqotpOJ21pGu
