### ISSUE TITLE
<PayPalCreditButton> Not working at all

### ISSUE THREAD

**Issue by rajat-android** [paypal/android-checkout-sdk#118]
<PayPalCreditButton> Always ineligible for all the users, I have Added <PayPalCreditButton> button in xml. but still can not able to load it as requirement. 

As per documentation and the Classes you provided , this must be helpful , but not working at all. 
Please have look.

**Comment by mahmoud-turki** [comment]
Hi @rajat-android,

Thank you for reporting the issue and I will be more than happy to help you! 

Do you happen to know if the `PayLater` button was eligible in all the use cases where the `PayPalCredit` button was ineligible? You should only see either PayLater button or PayPalCredit. There will never be a use case where the user is eligible for both PayLater and PayPalCredit at the same time.

**Comment by mahmoud-turki** [comment]
Hi @rajat-android,

I want to followup with you to see if you have any update for us. If it's no longer the issue I will close the ticket and feel free to reopen again. Thank you :)

**Comment by rajat-android** [comment]
We were a little busy at the time, And thought of doing another payment
gateway.
We still have that issue and the Simple Paypal button is working as
expected, but Paypal Later Button and Credit button eligibility always
comes up false and we are not able to see those buttons in the UI of App.
We will start work on that soon and I will let you know the status and if
we face any issues.
