### ISSUE TITLE
cardinalmobilesdk-2.2.4-1 Received status code 403 from server: Forbidden

### ISSUE THREAD

**Issue by JasonChiAT** [paypal/android-checkout-sdk#121]
* What went wrong:
Execution failed for task ':app:dataBindingMergeDependencyArtifactsDebug'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve org.jfrog.cardinalcommerce.gradle:cardinalmobilesdk:2.2.4-1.
     Required by:
         project :app > com.paypal.checkout:android-sdk:0.6.3
      > Could not resolve org.jfrog.cardinalcommerce.gradle:cardinalmobilesdk:2.2.4-1.
         > Could not get resource 'https://cardinalcommerceprod.jfrog.io/artifactory/android/org/jfrog/cardinalcommerce/gradle/cardinalmobilesdk/2.2.4-1/cardinalmobilesdk-2.2.4-1.pom'.
            > Could not GET 'https://cardinalcommerceprod.jfrog.io/artifactory/android/org/jfrog/cardinalcommerce/gradle/cardinalmobilesdk/2.2.4-1/cardinalmobilesdk-2.2.4-1.pom'. Received status code 403 from server: Forbidden

I have added credentials following by [document](https://developer.paypal.com/limited-release/native-checkout/android/#prepare-your-app) in root build.gradle, the issue happens randomly and is frequently these few days. Is Anything we can do to avoid this error?

**Comment by ChrisGuzman** [comment]
Hello,

We're currently investigating this and are in touch with Cardinal Commerce to resolve the issue. We'll provide you with updates here as they occur.

**Comment by tdchow** [comment]
Hi @JasonChiAT - This issue should now be resolved. I'm going to close out this issue, but please reply here if you're still seeing issues. Thanks!
