### ISSUE TITLE
Version 0.7.1 removes returnUrl from CheckoutConfig but then fails with missing returnUrl

### ISSUE THREAD

**Issue by SerggioC** [paypal/android-checkout-sdk#123]
**Describe the bug**
Version 0.7.1 of the SDK removes returnUrl from CheckoutConfig but then fails with missing returnUrl.

**To Reproduce**
1- Update to 0.7.1 which does not have returnUrl defined in the CheckoutConfig
2- Start Paypal payment.
3- Paypal opens external browser window to login and fails with error invalid client_id or redirect_url. check screenshot bellow.

**Expected behavior**
It should not show this error. and present the login page.

**Screenshots**
![Screenshot_20220718-101747_Brave](https://user-images.githubusercontent.com/21109275/179482285-92b8bc5c-7f23-475b-8fb9-fb0d3249884c.jpg)

**Smartphone (please complete the following information):**
 - Android Version: API 31
 - Device: S10+
 - Browser: Brave
 - SDK Version 0.7.1
 - Target SDK: 32
 - Compile SDK: 32

**Comment by tdchow** [comment]
Hey @SerggioC - thanks for reaching out. We're in the process of removing the returnUrl requirement from integrations with our SDK. We haven't made all of the backend changes yet.

To fix your integration with the 0.7.1 version, you can add `nativexo://paypalpay` as a return URL for your rest app in the PayPal Developer Portal. Can you try adding that and retrying your integration?

**Comment by SerggioC** [comment]
Just updated to 0.7.3 and the error is gone.
Thank you.
