### ISSUE TITLE
online crash in 0.5.4

### ISSUE THREAD

**Issue by terrence1991** [paypal/android-checkout-sdk#128]
Before you create a new issue, please search for similar issues. It's possible somebody has encountered this bug already. **PLEASE REMOVE THIS LINE TO ACKNOWLEDGE THAT AN ISSUE DOESN'T ALREADY EXIST FOR THIS BUG**

**Describe the bug**
Many users try to pay but failed.

**Expected behavior**
Caused by:
java.lang.IllegalStateException:Required value was null.
com.paypal.pyplcheckout.di.SdkComponent$Companion.getInstance(SdkComponent.kt:74)
com.paypal.pyplcheckout.di.SdkComponent$-CC.getInstance(SdkComponent.kt:0)
com.paypal.pyplcheckout.model.DebugConfigManager.getButtonVersion(DebugConfigManager.java:399)
com.paypal.pyplcheckout.instrumentation.InstrumentationEvent$InstrumentationEventBuilder.build(InstrumentationEvent.kt:141)
com.paypal.pyplcheckout.instrumentation.PLog.createBuilder(PLog.kt:390)
com.paypal.pyplcheckout.instrumentation.PLog.transition(PLog.kt:128)
com.paypal.pyplcheckout.instrumentation.PLog.transition$default(PLog.kt:124)
com.paypal.pyplcheckout.instrumentation.PLog.transition(Unknown Source:24)
com.paypal.pyplcheckout.home.view.BaseActivity.onCreate(BaseActivity.java:62)
com.paypal.pyplcheckout.home.view.activities.PYPLInitiateCheckoutActivity.onCreate(PYPLInitiateCheckoutActivity.java:39)

**Screenshots**
![image](https://user-images.githubusercontent.com/3390314/184271870-558e9a54-06e1-4549-8846-93973aa6817c.png)

![image](https://user-images.githubusercontent.com/3390314/184271097-c6753979-72ed-4052-9ec2-b0659f8f2285.png)

**Smartphone (please complete the following information):**
 - Android Version: [API 30,API 31]
 - Device: [samsung, pixel 6]
 - SDK Version [0.5.4]

**Additional context**

**Comment by ChrisGuzman** [comment]
Hello, the latest version is Version 0.7.3. Can you try again with that version? The latest version is always available to check via our [changelog](https://github.com/paypal/android-checkout-sdk/blob/main/CHANGELOG.md)

**Comment by tdchow** [comment]
Hey @terrence1991 - I believe this crash was resolved in a newer version of the SDK. We now have version 0.8.0 released. Please try that version and see if you're able to reproduce the crash. I'm going to close out the issue, but please respond here if you're still seeing the crash on the latest version. Thanks!
