### ISSUE TITLE
Showing Error page with "Invalid Scope" 

### ISSUE THREAD

**Issue by gkpatel461** [paypal/android-checkout-sdk#13]
I was unable to find a reason why this error comes. 
![WhatsApp Image 2021-05-31 at 5 27 07 PM](https://user-images.githubusercontent.com/25001927/120269872-3d23c680-c2c6-11eb-82cc-318a513cbcc7.jpeg)

Please help me to solve this. 
I have completely followed the document without any mistake.

**Comment by CodyEngel** [comment]
Hey @gkpatel461 please ensure that from your REST App underneath "Login With PayPal" and under the "Personal profile" section that both "Full name" and "Email" are checked. If they are checked both checked then please provide your client id so that I can look into this issue further.

**Comment by gkpatel461** [comment]
Thank you for your reply. But I am unable to get the "REST App underneath" for the Login with Paypal option. 
I just want to use the Paypal Checkout option as a payment gateway for the eCommerce Android App. No need for login with PayPal. 

Client ID: AXrxro3r5RiaVIK6rGZHxwMj_arNmQWqABQP7DhulP5NEKwc87MjYnH44MJHuzdGFP1xhle4YkUALYbM


Also, I have tried this demo app by adding a return URL per the document in the dashboard, but I am still getting the same error. 

Please help me to solve this.

**Comment by CodyEngel** [comment]
@gkpatel461 it looks like the Client ID is missing scopes that are granted after following the "Know Before You Code" section of our [official developer documentation](https://developer.paypal.com/docs/business/native-checkout/android/#know-before-you-code). Enabling Login with PayPal is necessary for the SDK to function as buyers will be redirected to PayPal to first login before they can see their account details.

**Comment by gkpatel461** [comment]
Thank you for your reply. Its worked. 
Is there an option for the user to pay using a card only without login into PayPal?

**Comment by CodyEngel** [comment]
@gkpatel461 happy to hear that worked. We currently only support authenticated PayPal flows, however once the buyer has logged in they should remain logged in for future purchases.

I'll go ahead and close this issue out.
