### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by anhy999** [paypal/android-checkout-sdk#131]
Before you create a new issue, please search for similar issues. It's possible somebody has encountered this bug already. **PLEASE REMOVE THIS LINE TO ACKNOWLEDGE THAT AN ISSUE DOESN'T ALREADY EXIST FOR THIS BUG**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Android Version: [e.g. API 30]
 - Device: [e.g. Emulator or One Plus 9]
 - Browser [e.g. chrome, safari] <- only applicable for app switches or fallback situations
 - SDK Version [e.g. 0.1.0]

**Additional context**

**Comment by ChrisGuzman** [comment]
Hello,
Please add more details to the bug report so we can investigate.

**Comment by tdchow** [comment]
Hey @anhy999 - I'm going to close out this issue. Please open a new issue and provide details so we can investigate. Thanks!
