### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by anhy999** [paypal/android-checkout-sdk#132]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ChrisGuzman** [comment]
Hello,
Please add more details to the feature request so we can investigate.

**Comment by tdchow** [comment]
Hey @anhy999 - I'm going to close out this issue. Please open a new issue and provide details so we can investigate. Thanks!
