### ISSUE TITLE
Paypal button not working with com.paypal.checkout:android-sdk:0.8.0

### ISSUE THREAD

**Issue by pascaprevost** [paypal/android-checkout-sdk#134]
Hi,
When I'm using "com.paypal.checkout:android-sdk:**0.6.1**", the Paypal button is working well in sandbox and Live environment.
![image](https://user-images.githubusercontent.com/15417623/187030363-07d3e434-8a22-44ab-907a-f25a8dab4e32.png)

When I'm using "com.paypal.checkout:android-sdk:**0.8.0**", there is a spinner on my PayPayl button and after 5 or 6 seconds, the button becomes invisible !!!
![image](https://user-images.githubusercontent.com/15417623/187030404-f1b84ad1-5a67-42cb-8086-9ebf0f8749ce.png)

What could explain this behavior ?

**Comment by ChrisGuzman** [comment]
Hello,

Thank you for your bug report. We will investigate and respond with our findings.

**Comment by ChrisGuzman** [comment]
We recently released version 0.8.1. Can you upgrade to that version and let us know if the issue still occurs?

**Comment by pascaprevost** [comment]
Unfortunately, with 0.8.1, I have the same issue, same behavior. There is a spinner on Paypal button and, after 5s, the button is automatically hidden.

**Comment by ChrisGuzman** [comment]
@pascaprevost can you please share the the package name of your app, if you're testing on sandbox or live, and the client ID you're using?

**Comment by pascaprevost** [comment]
- Package name : com.ppsoft.demo
- Sandbox Client Id : ARZ2Zcx6aRsVIErF4tZk-BgLn-13bxmCIXsDp89xFbIOl_Ebkk_917D5920ciuhgcj2x001Cr6EjRI82
- For your information, I have the same issue in Live and Sandbox environment.

**Comment by ChrisGuzman** [comment]
@pascaprevost The payment button for the funding type will not be visible if the funding type is not eligible. You may want to log out the `FundingEligibilityState` to learn more about the issue. Or you can try again with a different funding type. You can read more about the [PaymentButtonContainerViewState](https://developer.paypal.com/limited-release/paypal-mobile-checkout/android/customize-payment-button-container/#link-paymentbuttoncontainerviewstate) or [Payment button eligibility](https://developer.paypal.com/limited-release/paypal-mobile-checkout/android/customize-payment-buttons/#link-paymentbuttoneligibility)

If you still need more assistance can you share logs from the `PaymentButtonEligibilityStatus` or `PaymentButtonContainerViewState`

**Comment by pascaprevost** [comment]
Hi
Using PaymentButtonContainer instead of PaypalButton, it is working fine
Thank you for your help
