### ISSUE TITLE
Now SANDBOX is OK,but LIVE is not working

### ISSUE THREAD

**Issue by YBZzhangyanbin** [paypal/android-checkout-sdk#136]
I am integrating PayPal payment
Now SANDBOX is OK,but LIVE is not working
The error is  "This operation does not appear to be supported Please
return and report this error so that we can support you in the future.
(Invalid range)"
My Client ID is
AeJ407jpGvJ0xtTdt1JtDpKZJMSKLSk-6UK-Lh-JCtywuVZYxLXneOUXV8rv2hTH5YrXwTAeeoKkXRq3

The SDK I use is com.paypal.checkout:android-sdk:0.5.2

**Comment by YBZzhangyanbin** [comment]
![1091661481700_ pic](https://user-images.githubusercontent.com/38391834/187842756-0933c3f2-69f5-4d99-99b1-6d4b2c70f0b0.jpg)

**Comment by YBZzhangyanbin** [comment]
@tdchow here

**Comment by tdchow** [comment]
@YBZzhangyanbin - Thanks for reporting this in a new issue. I've added the missing scopes to your client ID. Can you try your live integration again and see if you get the same error?

**Comment by YBZzhangyanbin** [comment]
New Error 
This operation does not appear to be supported. Please return and report this error so that we can support you in the future. (Invalid client_id or redirect_uri)

**Comment by YBZzhangyanbin** [comment]
@tdchow 
> @YBZzhangyanbin - Thanks for reporting this in a new issue. I've added the missing scopes to your client ID. Can you try your live integration again and see if you get the same error?

**Comment by YBZzhangyanbin** [comment]
@tdchow 
Sorry to disturb you again

**Comment by tdchow** [comment]
@YBZzhangyanbin - no problem at all. I added the missing scopes for the above client ID. Can you try that integration again?

**Comment by YBZzhangyanbin** [comment]
Everything is normal here!Thanks!

**Comment by KingOfHui** [comment]
May I ask how you resolved it? I am also facing this problem now Could you please inform me
