### ISSUE TITLE
Can I load paypal webview in android just by call api and not config return url ? 

### ISSUE THREAD

**Issue by thehaodev** [paypal/android-checkout-sdk#138]
My app using the same API in below web. My senior told me just call API to show Paypal not config url in paypal button. But i read in documents that must config return url in DeveloperDashboard. What should I do ? 

![Picture](https://user-images.githubusercontent.com/112054658/188617892-48c0baf9-e3e6-441e-a0ab-201425924c79.png)

**Comment by ChrisGuzman** [comment]
Hello @thehaodev 

Apologies, I don't fully understand your request. We recently released version 0.8.1 which removes the requirement for a returnUrl. You can read [the changelog](https://github.com/paypal/android-checkout-sdk/blob/main/CHANGELOG.md#version-081) for more information

I also want to confirm that you are inquiring about the Android SDK that this repository concerns. Your screenshot shows you working on the web. If your question pertains to the Android SDK, please add more details to your request so we can help. Thanks.

**Comment by thehaodev** [comment]
Hello @ChrisGuzman 

Thanks for your replay. So my situation is I'm working with paypal in outsource project. The problem is when connect with Paypal from app we must config URL right ?. But in iOS they don't config. Then my senior told me just call api like web to connect with Paypal. So in short, my question is can I connect to Paypal just by call API from my server ? 
 
According to your response I update to version 0.8.1 where I don't need to config return URL. but it show the image like this.  
I use this account to login: 
CLIENT_ID: AX5AB8ne4WCvhwQwU0R1aw1Y5668lP1-slbCVgxm0W2k0_XEI3PB-uh8Dv7iOQcqsHpWGk7XL8QBS-rn
Paypal account: 
android@buyer.com
Pass: TECHUP100

Hope for your response and sorry for my previous unclear question. 
![image](https://user-images.githubusercontent.com/112054658/189258956-e6d288b0-f6f2-4a6e-8b51-79dbd76ef71b.png)

**Comment by ChrisGuzman** [comment]
@thehaodev Please try to clear the cache for your app and chrome (or the default browser) and try again. That may resolve the error in your screenshot

**Comment by thehaodev** [comment]
@ChrisGuzman Thank you so much Sir.
