### ISSUE TITLE
mijuu

### ISSUE THREAD

**Issue by ubuntubeki** [paypal/android-checkout-sdk#145]
Before you create a new issue, please search for similar issues. It's possible somebody has encountered this bug already. **PLEASE REMOVE THIS LINE TO ACKNOWLEDGE THAT AN ISSUE DOESN'T ALREADY EXIST FOR THIS BUG**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Android Version: [e.g. API 30]
 - Device: [e.g. Emulator or One Plus 9]
 - Browser [e.g. chrome, safari] <- only applicable for app switches or fallback situations
 - SDK Version [e.g. 0.1.0]
 - Package name of your app [e.g. com.example.my_app]
 - Client ID

**Additional context**

**Comment by ChrisGuzman** [comment]
Hi @ubuntubeki Please add more details if you're reporting a bug so that we can investigate.

**Comment by ubuntubeki** [comment]
paypal is so difficult for ethiopia

**Comment by mahmoud-turki** [comment]
@ubuntubeki Could you elaborate more on the issue please?

**Comment by saperi22** [comment]
@ubuntubeki please open a new ticket with the details of the bug.
