### ISSUE TITLE
dublicate class with  androix.lifecycle modules

### ISSUE THREAD

**Issue by halfaHalfawy** [paypal/android-checkout-sdk#146]
I added the debendency
this is my settings.gradle

`pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
        maven {
            url "https://cardinalcommerceprod.jfrog.io/artifactory/android"
            credentials {
                // Be sure to add these non-sensitive credentials in order to retrieve dependencies from
                // the private repository.
                username username_pa
                password password_pa
            }
        }
    }

    // This private repository is required to resolve the Cardinal SDK transitive dependency.

}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven {
            url "https://cardinalcommerceprod.jfrog.io/artifactory/android"
            credentials {
                // Be sure to add these non-sensitive credentials in order to retrieve dependencies from
                // the private repository.
                username username_pa
                password password_pa
            }
        }
    }
}

rootProject.name = "testpayment"
include ':app'
`

and this is my  app level  build.gradle 

`plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.testpayment'
    compileSdk 32

    defaultConfig {
        applicationId "com.example.testpayment"
        minSdk 23
        targetSdk 32
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

}

dependencies {

    implementation 'com.paypal.checkout:android-sdk:0.8.1'
    implementation 'androidx.appcompat:appcompat:1.5.1'
    implementation 'com.google.android.material:material:1.6.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.3'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'
}`
<img width="927" alt="image" src="https://user-images.githubusercontent.com/56086892/190913635-42c08a88-4ed2-4c81-84c6-721d5b18c066.png">

**Comment by halfaHalfawy** [comment]
[Processor] Library 'C:\Users\comupone\.gradle\caches\modules-2\files-2.1\com.paypal.android.sdk\data-collector\3.13.0\186fa09d77d6bd0d6fa09caff984f107557771\data-collector-3.13.0.aar' contains references to both AndroidX and old support library. This seems like the library is partially migrated. Jetifier will try to rewrite the library anyway.

**Comment by mahmoud-turki** [comment]
Hi @halfaHalfawy,

Thank you for reporting the issue. You can exclude the duplicated dependencies from the gradle and try again. If you still see this issue please let us know :)

**Comment by halfaHalfawy** [comment]
thanks @mahmoud-turki  
I exclude it and the paypal dependency then not work , after alot of serch I found that the error mainle was from google life-cycle modules , just downgrade the version and then it work
