### ISSUE TITLE
Vendor Email confirmation 

### ISSUE THREAD

**Issue by MAtech1850** [paypal/android-checkout-sdk#149]
I have an app that uses its services to sell products from within the app to users but every time a user tries to purchase a product, it says "vendor account doesnt have a verified email address paypal" any solution please?

**Comment by mahmoud-turki** [comment]
Hi @MAtech1850,

Thank you for reposting this issue. You will need to add your email address to PayPal dev portal as merchant and fill out all the information needed there and verify your email. If you still see this issue please report it on this portal https://www.paypal-community.com/t5/Sandbox-Environment/vendor-account-does-not-have-a-confirmed-email-address/td-p/2804018

I don't believe this issue related to the` android-checkout-sdk`. It more related to how your account should be setup probably. Please let us know if you have any additional questions and I will be more than happy to help :)

**Comment by mahmoud-turki** [comment]
Closing this issue as it's not relevant to `android-checkout-sdk` please feel free to reopen it if you need additional help :)
