### ISSUE TITLE
Request log in paypal scope permission

### ISSUE THREAD

**Issue by kebenxiaoming** [paypal/android-checkout-sdk#15]
We want to use paypal in our app.We have sent an email to help-loginappreview@paypal.com in order to obtain the email permission to log in with paypa,but it's been more than 10 days and we haven't received a reply.Our client_id is: AWpMbiZI8NKS7Fq9LfqLi2iQeLNBGbSlQilzGvl8EtMKPjvNy8xd3PaRZKeZ1H63_b3Ag-LmKIY_51RZ
Thanks a lot for your reply.

**Comment by CodyEngel** [comment]
Hey @kebenxiaoming thank you for reaching out, we're currently working with the team that handles the approvals. I'll be heading out on vacation after today however @mstuart or @tdchow should be able to help provide updates on this.

**Comment by kebenxiaoming** [comment]
@CodyEngel Thank you very much, the problem has been solved today.
