### ISSUE TITLE
Straight to order confirmation?

### ISSUE THREAD

**Issue by ajsherrell** [paypal/android-checkout-sdk#150]
**Is your feature request related to a problem? Please describe.**
User needs to be able to use PayPal button to make an order from the cart without clicking a 'place order' button in my app.

**Describe the solution you'd like**
Can I use PayPal to skip checkout and go directly to an order confirmation to place the order without having to click a 'place order' button in checkout?

**Describe alternatives you've considered**
I have tried to use Navigation to make this happen, but I am not able to do it so far. Is there a way to do this using the SDK? Or perhaps this has already been done by someone?

**Additional context**
This is an existing app that uses the PayPal SDK version 0.6.2

**Comment by mahmoud-turki** [comment]
Hi @ajsherrell,

Thank you for reporting the issue. Could you explain in details what is the current flow looks like and what exactly are you trying to do? Also, what button are you using? Is it the `Paymentbutton` & `PaymentButtonContainer` that we ship in the `android-checkout-sdk` or it's standalone button that you define inside your app?

**Comment by ajsherrell** [comment]
Hi @mahmoud-turki , 

Update: I am able to code to have PayPal skip checkout in my app, however, I would like an **option** to have the PayPal UI button to say something like "Place Order" or something equivalent. Currently the button to continue back to the app says 
"Review Order". Is this possible? Thanks.
![PpReviewOrderButton](https://user-images.githubusercontent.com/16841620/195354180-58907311-8774-47a7-b2a9-02c88f28ade5.png)

**Comment by ajsherrell** [comment]
I am tasked by my Project Manager to analyze if it is possible to skip the checkout screen after returning to our UI from the PayPal UI. This is to better improve the probability of the user to complete their order.

I actually do have the userAction set to **UserAction.PAY_NOW**. But I am still seeing the "Review Order" button label. Is this expected. How can I get the PayPal UI button label to say "Complete Purchase"? 

This is my setup:

`val checkoutConfig = CheckoutConfig(
                        application = app,
                        clientId = BuildConfig.PAYPAL_CLIENT_ID,
                        environment = BuildConfig.PAYPAL_ENVIRONMENT,
                        returnUrl = PAYPAL_RETURN_URL,
                        currencyCode = CurrencyCode.USD,
                        userAction = UserAction.PAY_NOW,
                        paymentButtonIntent = PaymentButtonIntent.CAPTURE,
                        settingsConfig = SettingsConfig(
                            loggingEnabled = true,
                            shouldFailEligibility = false
                        ),
                        uiConfig = UIConfig(showExitSurveyDialog = false)
                    )`

**Comment by mahmoud-turki** [comment]
When you say `"skip the checkout screen" ` are you referring to PayPal checkout screen that you attached above? Could you please attach a video for the current experience from start to end?

| How can I get the PayPal UI button label to say "Complete Purchase"?
You need to assign UserAction.PAY_NOW as well to the order itself when you create it. Are you starting the checkout with an order object or orderId?

**Comment by ajsherrell** [comment]
`When you say "skip the checkout screen" are you referring to PayPal checkout screen that you attached above?` --no, I mean the Checkout Screen in my app. I want to skip **my** Checkout Screen and go directly to **my** Order Completed Screen after the user clicks the "Complete Purchase"/"Review Order" button from the PayPal UI.

`Are you starting the checkout with an order object or orderId?` --I am starting checkout with the orderId. 

`Could you please attach a video for the current experience from start to end?` --I am in the process of asking my manager for permission to share a video to this platform. 

`You need to assign UserAction.PAY_NOW as well to the order itself when you create it.` --**How do I assign the userAction of PAY_NOW to the order itself?** I am currently using PayPal's CreateOrderAcitons class with the set(orderId: String) function: 

`PayPalCheckout.startCheckout(
                        createOrder = CreateOrder { _it: Create OrderActions_
                            it.set(data.processorTransactionId)
                        }
                    )`

**Comment by mahmoud-turki** [comment]
> **no, I mean the Checkout Screen in my app. I want to skip my Checkout Screen and go directly to my Order Completed Screen after the user clicks the "Complete Purchase"/"Review Order" button from the PayPal UI.**

Just to give a little bit of context here;
PayNow flow -> The PayPal button label will be "Complete Purchase", once the user hit that button we finish the checkout after we authorize the payment. Ideally the merchant should show complete order screen and nothing else needed from the user at this point.

Continue flow ->  The PayPal button label will be "Review Order", once the user hit that button we finish the checkout after we authorize the payment, then the user have to finalize the checkout on the merchant screen. why? bc in the flow sometimes the user might want to change shipping info and the merchant wanna update the tax or cart total...etc. Then the merchant should show the complete order screen.

> How do I assign the userAction of PAY_NOW to the order itself? I am currently using PayPal's CreateOrderAcitons class with the set(orderId: String) function:
I see, so it seems that the merchant backend create the order itself and return and orderId which is what you use to start the checkout experience. Could you check with your backend team what `userAction` they assign to the order? If they assign PayNow then you should see `complete purchase` but if they assign Continue then you should see `review order`

Hope that helps clearing any confusion :)

**Comment by AnAnD4T1** [comment]
@mahmoud-turki  how do you set user action in order creation api, i meant whats the key and value for that.

**Comment by mahmoud-turki** [comment]
@AnAnD4T1 There are two ways to set user action.

> how do you set user action in order creation api

1. On server side: When you create the order you should see `application_context` object which include `user_action` 
2. On client side: When you create the `CheckoutConfig()` you should see `user_action`

> i meant whats the key and value for that.

Please check the docs :)
1. On server side: https://developer.paypal.com/docs/api/orders/v2/#definition-application_context
2. On client side: https://developer.paypal.com/limited-release/paypal-mobile-checkout/android/

**Comment by ajsherrell** [comment]
Hi @mahmoud-turki ,

I have an update. I asked our backend developer to check what the user_action is set to. He discovered: "From backend, there is not value sent to PCS for paypal user action, but the acsURl received redirects to sandbox with user action as continue(Looks like default value from cardinal)."

As I mentioned earlier, I have the UserAction set to PAY_NOW in the CheckoutConfig() in my code. 

Here is how I have implemented it: 
`val checkoutConfig = CheckoutConfig(
                        application = app,
                        clientId = BuildConfig.PAYPAL_CLIENT_ID,
                        environment = BuildConfig.PAYPAL_ENVIRONMENT,
                        returnUrl = PAYPAL_RETURN_URL,
                        currencyCode = CurrencyCode.USD,
                        userAction = UserAction.PAY_NOW,
                        paymentButtonIntent = PaymentButtonIntent.CAPTURE,
                        settingsConfig = SettingsConfig(
                            loggingEnabled = true,
                            shouldFailEligibility = false
                        ),
                        uiConfig = UIConfig(showExitSurveyDialog = false)
                    )

                    PayPalCheckout.setConfig(checkoutConfig)
                    PayPalCheckout.startCheckout(
                        createOrder = CreateOrder {
                            it.set(data.processorTransactionId)
//                            it.create(createOrderRequest())
                        }
                    )
                    PayPalCheckout.registerCallbacks(
                        onApprove = OnApprove {
                            checkPayPalAuthentication()
                        },
                        onError = OnError {
                            setState(State.IDLE)
                            viewState.uiEvents.post(PayPalViewState.Event.Error(it))
                        },
                        onCancel = OnCancel {
                            setState(State.IDLE)
                            viewState.uiEvents.post(PayPalViewState.Event.Canceled)
                        }`

As a reminder, I need to have the button label in the PayPal UI as "Complete Purchase". It is currently "Review".

![PpReviewOrderButton](https://user-images.githubusercontent.com/16841620/197211744-7f2de360-b9bb-4100-bae8-1bdd94350cb4.png)
![PpCompletePurchase](https://user-images.githubusercontent.com/16841620/197211819-9629accb-30ac-4fe4-938a-8160c69b2def.png)

Here is what we are getting from the Cardinal acsUrl:
![user_action ](https://user-images.githubusercontent.com/16841620/197212371-4495b75c-8ba6-4bf4-a8a4-89a038426318.png)


This is the Cardinal lookup request to get acsUrl: 
![cardinal](https://user-images.githubusercontent.com/16841620/197212508-b8aeb972-683d-451b-a280-47e9d75347d5.png)


Please advise as to how we can get this default value from Cardinal changed to PAY_NOW. 

Thanks!

**Comment by AnAnD4T1** [comment]
@mahmoud-turki thanks

**Comment by tdchow** [comment]
Hi @AnandASanthosh - Sorry for the delay in response. Are you still looking for support on this issue?

**Comment by tdchow** [comment]
@AnandASanthosh - closing this issue for now. Feel free to respond here if you're still seeing the issue. Thanks!
