### ISSUE TITLE
PaymentButtonContainer is not inflating Android (0.8.1)

### ISSUE THREAD

**Issue by HafizAwaiskhan** [paypal/android-checkout-sdk#152]
**Describe the bug**
Using com.paypal.checkout.paymentbutton.PaymentButtonContainer with ('com.paypal.checkout:android-sdk:0.8.1') but its not rendering , inflating error in android.
How i can use that ? or there is some other approach ?

**To Reproduce**
add 'com.paypal.checkout:android-sdk:0.8.1'
then add <com.paypal.checkout.paymentbutton.PaymentButtonContainer
        android:id="@+id/payment_button_container"
        android:layout_width="match_parent"
        android:layout_height="100dp"
        app:paypal_button_color="silver"
        app:paypal_button_label="pay"
        app:paypal_button_shape="rectangle"
        app:paypal_button_size="large"
        app:paypal_button_enabled="true">

**Comment by mahmoud-turki** [comment]
Hi @HafizAwaiskhan,

Thank you for reporting the issue. Could you please replace the `100dp` height with `warp_content`. Also, implement the view state listener on the view and see what exception do you get then report it here so we know what is the actual reason for not rendering.

For example:

```
paymentButtonContainer.viewState = PaymentButtonContainerViewState.invoke(
                onLoading = { ->
                    Log.d(tag, tag.toString())
                },
                onFinish = { fundingEligibilityState, exception ->
                    fundingEligibilityState?.let {
                        Log.d(tag, fundingEligibilityState.toString())
                    }
                    exception?.let {
                        Log.d(tag, exception.message.toString())
                    }
                }
            )
```

**Comment by HafizAwaiskhan** [comment]
Hi @mahmoud-turki 
Thank you for reply .

D/nxoPayPalButton: eligibility status updated: Loading
D/nxoPayPalCreditButton: eligibility status updated: Loading
D/nxoPayLaterButton: eligibility status updated: Loading
-------------------------------------------------------------------------

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.cybermart.paypalcheckoutintegration/com.cybermart.paypalcheckoutintegration.MainActivity}: android.view.InflateException: Binary XML file line #10 in com.cybermart.paypalcheckoutintegration:layout/activity_main: Binary XML file line #10 in com.cybermart.paypalcheckoutintegration:layout/activity_main: Error inflating class com.paypal.checkout.paymentbutton.PaymentButtonContainer

and your method is not even called because its crashes in beginning.

**Comment by mahmoud-turki** [comment]
I see, it looks to me that you didn't set the config on your application level. `PayPalCheckout.setConfig(checkoutConfig: CheckoutConfig)`. Could you check if you have the config set probably on the application level and let me know?

**Comment by HafizAwaiskhan** [comment]
class MainActivity : AppCompatActivity() {
    lateinit var paymentButtonContainer: PaymentButtonContainer
    val TAG = "paypal"

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        paymentButtonContainer = findViewById(R.id.payment_button_container)
        val config = CheckoutConfig(
            application = application,
            clientId = "AY_DPizCxyvnG91I1jHgN4A4TC5KwtFOaEyuIGkdb9Wz638V1t3W5Pnq3oALaFaz0CjYnuXWT2-nOJCa",
            environment = com.paypal.checkout.config.Environment.SANDBOX,
            currencyCode = CurrencyCode.USD,
            userAction = UserAction.PAY_NOW,
            settingsConfig = SettingsConfig(
                loggingEnabled = true
            )
        )
        PayPalCheckout.setConfig(config)

        paymentButtonContainer.paypalButtonEnabled = true
        paymentButtonContainer.setup(
            createOrder =
            CreateOrder { createOrderActions ->
                val order =
                    Order(
                        intent = OrderIntent.CAPTURE,
                        appContext = AppContext(userAction = UserAction.PAY_NOW),
                        purchaseUnitList =
                        listOf(
                            PurchaseUnit(
                                amount =
                                Amount(currencyCode = CurrencyCode.USD, value = "10.00")
                            )
                        )
                    )
                createOrderActions.create(order)
            },
            onApprove =
            OnApprove { approval ->
                approval.orderActions.capture { captureOrderResult ->
                    Log.i("CaptureOrder", "CaptureOrderResult: $captureOrderResult")
                }
            },
            onCancel = OnCancel {
                Log.d("OnCancel", "Buyer canceled the PayPal experience.")
            },
            onError = OnError { errorInfo ->
                Log.d("OnError", "Error: $errorInfo")
            }
        )
    }
}

Here is my main class ! can you please check what is wrong ?

**Comment by mahmoud-turki** [comment]
The config should be set on the application level before you start the MainActivity otherwise you will get exception.

**Comment by HafizAwaiskhan** [comment]
thank you
