### ISSUE TITLE
There is a problem when I compile and install

### ISSUE THREAD

**Issue by panguojian** [paypal/android-checkout-sdk#16]
**Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find android.arch.lifecycle:extensions:2.1.0.**
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/android/arch/lifecycle/extensions/2.1.0/extensions-2.1.0.pom
       - https://repo.maven.apache.org/maven2/android/arch/lifecycle/extensions/2.1.0/extensions-2.1.0.pom
       - https://oss.sonatype.org/content/repositories/snapshots/android/arch/lifecycle/extensions/2.1.0/extensions-2.1.0.pom
       - https://cardinalcommerceprod.jfrog.io/artifactory/android/android/arch/lifecycle/extensions/2.1.0/extensions-2.1.0.pom
       - file:/C:/Users/Administrator/.m2/repository/android/arch/lifecycle/extensions/2.1.0/extensions-2.1.0.pom
     **Required by:
         project :app > com.paypal.checkout:android-sdk:0.2.0
   > Could not find android.arch.lifecycle:runtime:2.1.0.**
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/android/arch/lifecycle/runtime/2.1.0/runtime-2.1.0.pom
       - https://repo.maven.apache.org/maven2/android/arch/lifecycle/runtime/2.1.0/runtime-2.1.0.pom
       - https://oss.sonatype.org/content/repositories/snapshots/android/arch/lifecycle/runtime/2.1.0/runtime-2.1.0.pom
       - https://cardinalcommerceprod.jfrog.io/artifactory/android/android/arch/lifecycle/runtime/2.1.0/runtime-2.1.0.pom
       - file:/C:/Users/Administrator/.m2/repository/android/arch/lifecycle/runtime/2.1.0/runtime-2.1.0.pom
     Required by:
         project :app > com.paypal.checkout:android-sdk:0.2.0

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

**Comment by tdchow** [comment]
Hey @panguojian! Thanks for reaching out. I'm currently looking into the issue.

In the meantime, would you be able to share your project's build.gradle files?

**Comment by tdchow** [comment]
@panguojian - I was able to reproduce the issue and am currently working on a fix. I hope to have a snapshot build for you to try out early next week. Will keep you updated!

**Comment by panguojian** [comment]
I suspect this problem is related to the gradle version

**Comment by tdchow** [comment]
@panguojian I found a workaround that should allow you to successfully build with the Checkout SDK.

In your project's gradle.properties file, add the following lines:
```
android.enableJetifier=true
android.useAndroidX=true
```

`enableJetifier=true` is required to force the use of AndroidX libraries. I'm still working on a fix that will remove the need for Jetifier, but hopefully, this will unblock you!

**Comment by tdchow** [comment]
Closing this issue.
