### ISSUE TITLE
Dont work in Live environment

### ISSUE THREAD

**Issue by eriodesign** [paypal/android-checkout-sdk#170]
Recently I integrated PayPal in my application . Everything works fine in sandbox but i got ( Invalid client_id or redirect_uri  ) error in my Live environment.
client_id: AcJevGxT4sKQEKmmXf5N2gN21dXVkl9qhXxgdhJtR2qwajIihPZmfvcD1iXgHZy6rpKH8Q8ntVuZSBzz
Can you please help me ?

**Comment by PostLiu** [comment]
hello,I have the same problem, have you solved it?

**Comment by Pannarrow** [comment]
> hello,I have the same problem, have you solved it?

Brother, did you solve it?
