### ISSUE TITLE
I encountered a problem. When I make the phone's network unavailable, PaypalButton shows loading, which is normal. But when I make the mobile network available, PaypalButton still shows loading. Even restarting the app will not solve this problem.

### ISSUE THREAD

**Issue by panguojian** [paypal/android-checkout-sdk#18]
I encountered a problem. When I make the phone's network unavailable, PaypalButton shows loading, which is normal. But when I make the mobile network available, PaypalButton still shows loading. Even restarting the app will not solve this problem.

**Comment by tdchow** [comment]
Thanks for reporting this @panguojian. I was able to reproduce the issue but was seeing the PaypalButton load properly after restarting the app (when the Activity containing the PaypalButton is recreated).

I've added an item to our backlog to gracefully handle changes in network connectivity.

**Comment by tdchow** [comment]
The work has been picked up and should be in the next release of the SDK.

**Comment by tdchow** [comment]
Hey @panguojian. The 0.4.0 release is out. This release added a network listener to the payment button. Now when a buyer gains connection, the payment button will render.

```
implementation 'com.paypal.checkout:android-sdk:0.4.0'
```

**Comment by tdchow** [comment]
Closing this issue. @panguojian, feel free to respond here if you're having issues with the Payment Button responding to network status.
