### ISSUE TITLE
How can i make sure a client pays another ? 

### ISSUE THREAD

**Issue by SouhailKrs** [paypal/android-checkout-sdk#183]
I'm working on an android app ( using Nodejs for backend ) where customers sell and buy products from each other ( a market place ) .

For example :

Customer A is selling a product

Customer B is going to buy the product that A is selling and going to pay him using PayPal .

How can I make this transaction happen and make sure the money goes to A .

**Comment by saperi22** [comment]
We don't support P2P transactions today.

On the other hand, if you, as the market place provider are taking money, then you would act as the merchant. You'd then move the money to user A. E.g.: Think Etsy.

**Comment by SouhailKrs** [comment]
Thank you !
