### ISSUE TITLE
The PayPal client is installed, but now you can only call the web payment in the app

### ISSUE THREAD

**Issue by kebenxiaoming** [paypal/android-checkout-sdk#21]
The PayPal client is installed, but now you can only call the web payment in the app.

Can we call the client on the mobile phone with PayPal client, and then call the web page without the client.

This makes the user feel more optimized.

**Comment by CodyEngel** [comment]
Hey @kebenxiaoming can you provide additional details when you say:
> but now you can only call the web payment in the app

Are you talking about authentication with the Checkout SDK going through a web browser as opposed to the PayPal Android app or something else?

**Comment by kebenxiaoming** [comment]
@CodyEngel Yes, is it possible to log in and pay only through a web browser. Can we call the client on the mobile phone with PayPal client, and then call the web browser without the client?

**Comment by CodyEngel** [comment]
@kebenxiaoming login without a browser switch is not something we have plans of supporting as it would deviate from best practices for OAuth 2.0.

**Comment by kebenxiaoming** [comment]
@CodyEngel Thank you for your reply.
