### ISSUE TITLE
Phone no of shipping details received in masked format.

### ISSUE THREAD

**Issue by psandeepkumar-concentrix** [paypal/android-checkout-sdk#211]
**General information**
Environment: Debug
OS: Android

**Issue description**
onApproval Success callback the provided Shipping Address Details **Phone No** coming in **masked format** earlier couple of months ago we  used to receive in phone no in unmasked format.

`[Phone(number=4*****7084), Phone(number=4*****8200)]

Note: Kindly give a needful solution for this.
`

**Comment by tdchow** [comment]
Hey @psandeepkumar-concentrix - there was a change on our backend to mask this data due to security reasons. I'm going to close this issue out. 

If the unmasked phone number is needed, can you please provide the use case you have for the entire phone number? Thanks!

**Comment by sholsinger** [comment]
@tdchow Order Management systems often require phone numbers so businesses can contact their customers easily if there is an issue with a customer's order. SMS order notifications is another reason customers might want to share their phone number with the merchant they're working with.
