### ISSUE TITLE
ReturnURL configuration missing in portal

### ISSUE THREAD

**Issue by senj** [paypal/android-checkout-sdk#236]
According to the documentation, we can configure app returnUrl link in the portal.

![image](https://user-images.githubusercontent.com/5556013/236195605-bbb7694e-47a1-4700-8e9c-d0b32af953af.png)

This already worked for us, but it seems there is a new UI and now the config is missing!

![image](https://user-images.githubusercontent.com/5556013/236208390-e1fd0609-39b8-49ea-8db0-eb7898c8dc6c.png)

We went live with our app today and are not able to configure the link :(

**Comment by senj** [comment]
I found it in the "Log in with PayPal" Section.

**Comment by pingv** [comment]
I think the documentation should be fixed. There's no clear indication that the returnURL is hidden into "Log in with PayPal"

> https://www.paypal.com/us/cshelp/article/how-do-i-set-a-redirect-url-for-login-with-paypal-ts1995#:~:text=You%20can%20find%20your%20return,environment%20you're%20working%20in.
