### ISSUE TITLE
Paypal android checkout sdk gives invalid scope in live mode

### ISSUE THREAD

**Issue by lorenzolopez928** [paypal/android-checkout-sdk#24]
I am developing an android application which includes in-app Paypal payments for buying coins.
I am using the latest version 0.3.0.
I am facing the following error when clicking Paypal Button in LIVE mode
![Screenshot_2021-07-06-12-51-15](https://user-images.githubusercontent.com/11564940/126393562-6bbe5cec-2425-4bff-8262-ea726cc7cfe0.png)

I have the following configuration in my code:
```
val environment: Environment = if (resources.getBoolean(R.bool.production)) Environment.LIVE else Environment.SANDBOX
val config = CheckoutConfig(
        this,
        getString(R.string.paypal_client_id), environment,
        "by.the.way://paypalpay", CurrencyCode.USD, UserAction.PAY_NOW,
        SettingsConfig(
                true,
                false
        )
)
setConfig(config)
```
This is the code for buying coins:
```
btnPaymentPayPal.setup(object : CreateOrder {
            override fun create(createOrderActions: CreateOrderActions) {
                val purchaseUnits = ArrayList<PurchaseUnit>()
                purchaseUnits.add(
                        PurchaseUnit.Builder()
                                .amount(
                                        Amount.Builder()
                                                .currencyCode(CurrencyCode.USD)
                                                .value(coinsPakageModel.price.toString())
                                                .build()
                                )
                                .description(coinsPakageModel.name)
                                .build()
                )
                val order: Order = Order.Builder().appContext(
                        AppContext.Builder()
                                .userAction(UserAction.PAY_NOW)
                                .build()
                ).intent(OrderIntent.CAPTURE)
                        .purchaseUnitList(purchaseUnits).build()
                createOrderActions.create(order)
            }
        },
                object : OnApprove {
                    override fun onApprove(approval: Approval) {
                        approval.orderActions.capture(object : OnCaptureComplete {
                            override fun onCaptureComplete(result: captureOrderResult) {
                              //...
                            }
                        })
                    }
                },
                object : OnCancel {
                    override fun onCancel() {
                        //...
                    }
                },
                object : OnError {
                    override fun onError(errorInfo: ErrorInfo) {
                        //...
                    }
                }
        )
```
And this is my Paypal Configuration in developers dashboard. My account is a business account :
![javierfiguerasm_1-1626812818709](https://user-images.githubusercontent.com/11564940/126394058-a0eac757-9084-4838-a3fe-a2a2db8b8ff7.png)
![javierfiguerasm_2-1626812842945](https://user-images.githubusercontent.com/11564940/126394062-22c0817b-23c6-41bc-9035-98d7dc848275.png)
![javierfiguerasm_3-1626812920165](https://user-images.githubusercontent.com/11564940/126394063-ffa624d6-be5e-4462-aed3-73abdf9e6c4d.png)
![javierfiguerasm_0-1626812684530](https://user-images.githubusercontent.com/11564940/126394065-8d8bd44b-6e4b-4a65-81f6-25c52d6b4892.png)

**Comment by CodyEngel** [comment]
@lorenzolopez928 thank you so much for such a detailed report! It looks like the personal profile is only requesting full name instead of full name and email. Checking email should resolve the issue -- sometimes it can take up to 3 hours for new scopes to propagate so if you don't see the issue resolved immediately please give it a few hours.

I'm closing the issue for now as this has been a common report we've gotten. If this doesn't resolve your issue please feel free to re-open and tag me.

**Comment by lorenzolopez928** [comment]
Thank you very much for the fast response. But I can't mark the email option in LIVE mode, Paypal says that for email requesting I have to pass the review process. It's that true?

**Comment by lorenzolopez928** [comment]
I archived to pass the PayPal review process, It was very straightful and difficult.
