### ISSUE TITLE
Your app is using the Cardinal Commerce SDK  upgrading to 2.2.7-2

### ISSUE THREAD

**Issue by abdulmanum** [paypal/android-checkout-sdk#254]
I am using android checkout sdk i tried all paypal checkout SDK versions 0.6.2 , 0.112.2 but below error everytime

Issue with your app
Your app is using the Cardinal Commerce SDK which collects but may not be limited to Android ID and Hardware IDs identifiers. Persistent device identifiers may not be linked to other personal and sensitive user data or resettable device identifiers.You may consider moving to another SDK; removing this SDK; or if available from your SDK provider, upgrading to a policy-compliant version of this SDK that does not include the violating code.According to the information provided by your SDK provider, you may consider upgrading to 2.2.7-2. Please consult the SDK provider for further information.

**Comment by saperi22** [comment]
Cardinal SDK was upgraded to 2.2.7-2 in 0.8.7 version. 
Please check the changelog: https://github.com/paypal/android-checkout-sdk/blob/main/CHANGELOG.md#version-087

**Comment by saperi22** [comment]
Closing as there's not been any activity for a while.
