### ISSUE TITLE
apk work fine but boundle is crach with latest version  

### ISSUE THREAD

**Issue by MohammedTohamyGazzar** [paypal/android-checkout-sdk#263]
Caused by android.content.res.Resources$NotFoundException
String resource ID #0x7f12029e

**Comment by lkant8** [comment]
Can I fix this issue ?

**Comment by MaxHastingsPP** [comment]
If you are still running into this issue please provide us with the following information.

- Environment - sandbox or live?
- SDK version
- Android version
- Stack trace or error logs
- Screenshots or screen recording
- Steps to reproduce the issue.

Thank you!
