### ISSUE TITLE
lateinit property accessToken has not been initialized

### ISSUE THREAD

**Issue by leon2017** [paypal/android-checkout-sdk#28]
When we wake up SDK payment, we always encounter an occasional crash. The crash log is as follows：
`UncaughtException: kotlin.UninitializedPropertyAccessException: lateinit property accessToken has not been initialized`

**Comment by tdchow** [comment]
Hey @leon2017! Could you try pulling in the latest version of the SDK? We just released 0.4.0 which should address this crash.

```
implementation 'com.paypal.checkout:android-sdk:0.4.0'
```

**Comment by leon2017** [comment]
> Hey @leon2017! Could you try pulling in the latest version of the SDK? We just released 0.4.0 which should address this crash.
> 
> ```
> implementation 'com.paypal.checkout:android-sdk:0.4.0'
> ```

Thank you. I'll try

**Comment by tdchow** [comment]
Closing this issue. @leon2017 let me know if you continue to see issues with the latest version of the SDK.
