### ISSUE TITLE
Payment Button status always returns error on version 0.4.0

### ISSUE THREAD

**Issue by mikasR** [paypal/android-checkout-sdk#30]
Hi @CodyEngel,

After migrating to version 0.4.0 the payment button always appears loading and the gets hidden.
I have this code to make a log:
payPal.setPaymentButtonEligibilityStatusChanged(paymentButtonEligibilityStatus -> Log.i("PaymentButtonEligibility", String.format("paymentButton : %s", paymentButtonEligibilityStatus)));

The output is the following:
2021-08-09 14:48:40.733 23927-23927/pt.zonesoft.biip I/PaymentButtonEligibility: paymentButton : Loading
2021-08-09 14:49:10.778 23927-23927/pt.zonesoft.biip I/PaymentButtonEligibility: paymentButton : Error

 - Android Version: API 30
 - Device: Emulator
 - SDK Version 0.4.0

**Comment by tdchow** [comment]
Hey @mikasR! An additional parameter was added to the `CheckoutConfig` that's used for the payment button eligibility. Can you try setting this value and see if the payment button is shown?

```kotlin
val config = CheckoutConfig(
    ...
    paymentButtonIntent = PaymentButtonIntent.CAPTURE // or PaymentButtonIntent.AUTHORIZE
)
```

**Comment by mikasR** [comment]
Hi,
Yes. I have set it as CAPTURE, but the result is the same.
At least on the decompiled sdk code there seems to be a bug. I noticed there’s some code setting the elegibility as Error everytime the button is initialized.

**Comment by tdchow** [comment]
Hm. There's an Android version code check that sets the eligibility status in the init block. 

```kotlin
eligibilityStatus = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) Loading else Ineligible
```

Are you using the `PayPalButton` variant of the `PaymentButton`?

**Comment by mikasR** [comment]
Yes, i am using PayPalButton.

I found the problem.

In the documentation, it says that this code must be put on the Application class

```
CheckoutConfig config = new CheckoutConfig(this, ...);
PayPalCheckout.setConfig(config);
```

This used to work fine prior to version 0.4.0.

What happens now is that this code gets executed when the app launches, which executes the following in PayPalCheckou.kt:
```
private fun retrieveFundingEligibility(intent: PaymentButtonIntent?) {
        CoroutineScope(Job() + Dispatchers.Main).launch {
            val response = sdkComponent.retrieveFundingEligibilityAction.retrieve(intent)
            DebugConfigManager.getInstance().fundingEligibilityResponse = response
            if (response != null) {
                Events.getInstance().removeListener(NetworkEventTypes.NETWORK_AVAILABILITY, networkEventListener(intent))
                Events.getInstance().fire(PayPalEventTypes.FUNDING_ELIGIBILITY_RESPONSE, Success(response))
            }
        }
    }
```

As for in the PaymentButton.kt, we find this:
```
handler.postDelayed(noEligibilityRunnable, RETRY_TIMEOUT)
Events.getInstance().listen(PayPalEventTypes.FUNDING_ELIGIBILITY_RESPONSE, eligibilityEventListener)
```
What happens is that this code` Events.getInstance().fire(PayPalEventTypes.FUNDING_ELIGIBILITY_RESPONSE, Success(response))` runs way before the code on the payment button. The payment button will never receive this `Events.getInstance().listen(PayPalEventTypes.FUNDING_ELIGIBILITY_RESPONSE, eligibilityEventListener)` hence the noEligibilityRunnable gets executed.

The solution is to put the sdk initialization on the same activity code where the button is. That solved my problem.

However i think this may be a bug, since the SDK is only meant to be initialized once (as the documentation says).
So you must either change this behaviour or update the documentation.

**Comment by tdchow** [comment]
Thanks so much for the detailed investigation!

You should be safe setting the config in your Activity instead of the Application class. We initially recommended setting the config in the application class to frontload that eligibility call. 

I'll create a ticket for our backlog to fix this behavior when setting the config in the Application class. 

Thanks again for quickly reporting this and for finding the root cause!
