### ISSUE TITLE
PayPalButton quickly click the page to disappear

### ISSUE THREAD

**Issue by androidGithubRookie** [paypal/android-checkout-sdk#31]
Click the button PayPalButton continuously and the page disappears without displaying，PayPalButton don't do continuous click exception handling

**Comment by tdchow** [comment]
Hey @androidGithubRookie! I added a ticket to our backlog to handle multiple clicks of the PaymentButton. This should be fixed in our next scheduled release.

**Comment by tdchow** [comment]
@androidGithubRookie - This is now resolved in the latest version of the SDK!

```
implementation 'com.paypal.checkout:android-sdk:0.4.1'
```

**Comment by tdchow** [comment]
Closing this issue. @androidGithubRookie - let me know if you have issues with the latest version of the SDK.
