### ISSUE TITLE
Problem with version 0.4

### ISSUE THREAD

**Issue by mikasR** [paypal/android-checkout-sdk#33]
After updating the SDK to version 0.4.0 and 0.4.1 all transactions on the LIVE environment started failing with the error on the screenshot. This happens right after tapping on the PayPalButton.
Prior to this update, everything was working fine. We also have an iOS implementation using the same account and it works ok.

![image](https://user-images.githubusercontent.com/10234099/129930346-00dc6034-0cac-44db-a9a1-ca229f695121.png)

 - Android Version: API 30
 - Device: Mulitple devices
 - SDK Version 0.4.0 and 0.4.1

**Comment by jcnoriega** [comment]
HI! could you provide a code snippet in how you are configuring the sdk?

**Comment by mikasR** [comment]
```
CheckoutConfig config = new CheckoutConfig(getApplication(), BuildConfig.PCID, BuildConfig.DEBUG ? Environment.SANDBOX : Environment.LIVE,
                BuildConfig.APPLICATION_ID + "://paypalpay", CurrencyCode.EUR, UserAction.PAY_NOW, PaymentButtonIntent.CAPTURE, new SettingsConfig(BuildConfig.DEBUG, false));
        PayPalCheckout.setConfig(config);
```

**Comment by tdchow** [comment]
Hey @mikasR - Would you be able to provide me your Live clientId? I can take a look and see if your Live app is set up correctly.

**Comment by mikasR** [comment]
Is there a way i can send you the clientID in a private message?

**Comment by tdchow** [comment]
Yep, feel free to email me at tichow@paypal.com.

**Comment by mikasR** [comment]
Sent...

**Comment by jianjun8421** [comment]
how to fix this ? I have the same problem

**Comment by ChrisGuzman** [comment]
Hi @jianjun8421 
The latest version of the SDK is [0.6.3](https://github.com/paypal/android-checkout-sdk/blob/main/CHANGELOG.md#version-063) please try to upgrade to that version and if you need to report a bug or unexpected behavior please open a new issue.

**Comment by jianjun8421** [comment]
ok. Thanks your reply. 
















At 2022-07-06 09:22:47, "Chris Guzman" ***@***.***> wrote:

Hi @jianjun8421
The latest version of the SDK is 0.6.3 please try to upgrade to that version and if you need to report a bug or unexpected behavior please open a new issue.
