### ISSUE TITLE
How to specify the payee with the android-checkout-sdk?

### ISSUE THREAD

**Issue by wcoopg** [paypal/android-checkout-sdk#34]
In IOS I used: `PurchaseUnit(payee: PurchaseUnit.Payee(merchantId: someMerchantID))`. But in Android I can't find this option

**Comment by tdchow** [comment]
Hey @wcoopg. I created a ticket for adding `Payee` to the `PurchaseUnit` class. I'll also make sure that we match iOS's `OrderRequest`. 

I'll update you here once the changes have been released.

**Comment by wcoopg** [comment]
@tdchow Thank you for your reply.

**Comment by tdchow** [comment]
Hey @wcoopg - Just wanted to let you know that the work has been completed and will be in the next release.

**Comment by jcnoriega** [comment]
@wcoopg New version 0.4.5 containts current feature

**Comment by jcnoriega** [comment]
Resolved, closing issue
