### ISSUE TITLE
Click the payment button when there is no network, and the application crashes

### ISSUE THREAD

**Issue by rancekk** [paypal/android-checkout-sdk#40]
Click the payment button when there is no network, and the application crashes
![919b0a6ba62ef2fa750e092e0c755dc](https://user-images.githubusercontent.com/23482942/130914400-b13bc5f3-c832-4361-9cf0-978f14d55abe.png)
![63250545c938d00f14b7b0c140c54ca](https://user-images.githubusercontent.com/23482942/130914413-c1e1eaff-d281-47c2-8acc-bc21ae5a3c1f.png)

**Comment by w1532106001** [comment]
@jcnoriega airplane mode

**Comment by jcnoriega** [comment]
@w1532106001 thank you, taking a look at it now

**Comment by w1532106001** [comment]
The crash is gone. Thanks
