### ISSUE TITLE
Only Published App can pass the app review request to pay in live environment?

### ISSUE THREAD

**Issue by A-10ng** [paypal/android-checkout-sdk#41]
Only Published App (eg: In Google Play, Apple Store, Huawei Application Market and so on) can pass the app review request to pay in live environment? 

It work fine in sandbox mode, but when I switch to live mode, it shows the error "invalid scope"(issue #24 ).

I send the email to ur team and got the error msg:
Access denied to your site/application.

Hope u can answer my question!

**Comment by A-10ng** [comment]
Client ID:
AY3hM8sy5y6C6dTcqZQNzFTPAa3LjLX4tHkE77g2ve4hrRBWHkj_8SacjCGAyDXPdM2pjQQxWH3yXmry

**Comment by tdchow** [comment]
@A-10ng Thanks! I just reached out to an internal team to get this issue resolved. Will have an update soon.

**Comment by tdchow** [comment]
Hey @A-10ng, I just heard back from the internal team. Could you try your integration again with the Live environment?

**Comment by A-10ng** [comment]
It stuck at "Securely Logging You In..."( even I clear my browser's cache and cookie or uninstall my app), but  I can login in web page (an approve link, eg:https://www.paypal.com/checkoutnow?token=xxxxxxxxxxx)
<img width="361" alt="企业微信截图" src="https://user-images.githubusercontent.com/32977668/131452882-af0d1f76-5b84-45b5-93ae-5b455eeb558a.png">

Should I add this scope? Hope u can give me a solution, thx!
![企业微信截图1](https://user-images.githubusercontent.com/32977668/131453124-ea30b77a-c92b-4570-88ab-ea5888668e04.png)

**Comment by A-10ng** [comment]
It runs well. Thx!

**Comment by tdchow** [comment]
No worries! Glad I was able to resolve the issue for you!

**Comment by MilanGhimire666** [comment]
Hey @tdchow I also got the same problem. Can you please help me resolve this ?
