### ISSUE TITLE
Invalid Scrope on PayPal.com Page in Chrome

### ISSUE THREAD

**Issue by Sidd-dev-android** [paypal/android-checkout-sdk#44]
When I run this code after cloned it. Then Change my Client & Secret Key Live after that on the Client Integration button click open create order page after filling all forms then Submit it redirect on Paypal.com page but showing invalid scope nothing performs. Please see a screenshot from the attachment.

![image_2021_09_02T04_10_24_240Z](https://user-images.githubusercontent.com/72066132/131784510-c0baf1ea-b5b0-4cdd-ab33-3a4b65ef86f3.png)

**Comment by tdchow** [comment]
Hi @Sidd-dev-android - You'll need to perform these steps in order for your ClientId and Secret to work in this demo app: https://developer.paypal.com/docs/business/native-checkout/android/#know-before-you-code

Going to close out this issue, but feel free to open a new one if you encounter any issues!
