### ISSUE TITLE
when second time enter the page,the payment button ,it will disappear,or can not  display.

### ISSUE THREAD

**Issue by chenyao1208** [paypal/android-checkout-sdk#46]
When  i first click payment button is OK ，will enter login page ,but back to  home page ,second enter payment page，the  payment button is just loading ,and  can not display. 

![微信图片_20210902172129](https://user-images.githubusercontent.com/21217350/131819087-9b3b2ac8-29ea-4441-ac7f-758c9743f32c.png)
![微信图片_20210902172205](https://user-images.githubusercontent.com/21217350/131819103-d52b55aa-5c5c-4bc3-94f0-cc00cb70dc8d.png)
![微信图片_20210902172233](https://user-images.githubusercontent.com/21217350/131819123-d1a1fc64-b0ea-434f-a268-e39e8ba2a72a.png)

this is logcat shows
![微信图片_20210902172048](https://user-images.githubusercontent.com/21217350/131819169-9d471c9d-c7b0-4b0c-b8a1-7bd40daff1ab.png)

 - SDK Version 0.4.3

**Comment by RaffaLinux** [comment]
Hi @jcnoriega i can confirm that even with the latest sample project changing activity or fragment causes the button to be stuck in loading and then disappear

**Comment by chenyao1208** [comment]
Hi @jcnoriega  I upgrade to 0.4.4 and it's still there.

**Comment by chenyao1208** [comment]
this is log
![image](https://user-images.githubusercontent.com/21217350/131960908-41842581-344f-4fda-adf3-6accc724e2b6.png)

**Comment by vientn1998** [comment]
me too, please help me @jcnoriega

**Comment by tnv1998** [comment]
The same error. plz fix it thank you

**Comment by tnv1998** [comment]
The same error. plz fix it thank you

**Comment by A-10ng** [comment]
The same error with more log

**Comment by faiz106** [comment]
I was having the same issue until i downlgraded to 0.20 version

   implementation'com.paypal.checkout:android-sdk:0.2.0'

**Comment by jcnoriega** [comment]
Hi! Thank you so much for reporting. A pull request to fix this has been created and it will be included on the next release next week. 
The bug happens when `PayPalCheckout.setConfig()` is called in the `Application` class. A quick workaround this, is to call `setConfig()` on the same activity that renders the `PaymentButton`.

**Comment by jcnoriega** [comment]
Version 0.4.5 is deployed with the fix. Please confirm if issue persists
