### ISSUE TITLE
paymentButton - onApprove, onCancel not invoked

### ISSUE THREAD

**Issue by mikasR** [paypal/android-checkout-sdk#5]
After setting up everything on my paypal account, i am able to use the paymentButton to start the payment.

However, after the authorization my app does not come to the foreground. The same happens if i cancel the payment process.

I verified and all the return URIs are correctly configured.

In iOS a don't have any problem, only on Android.

**Comment by CodyEngel** [comment]
Hey @mikasR can you provide some additional information so we can help troubleshoot this issue?

- Please provide a screenshot of what you seeing when the app does not come back to the foreground.
- Please provide code snippets of your Android integration including: the SDK initialization and the payment button's setup function.
- If possible, please provide the sandbox client id so that I can verify the REST app settings.

**Comment by mikasR** [comment]
Hello @CodyEngel,

I'm sorry for the late response.

I am experiencing this issue directly on the sample app, so the code is the code of the sample app.

The sandbox client id is the following:
AdypFir7Wx7kgw1Q9CLGjH8OGa-znGnpjA6zTvJoz6jV4XT51PL_5g9FHP0q84GjgqNozzX36hGuXrJc

![image](https://user-images.githubusercontent.com/10234099/115521891-80305a00-a283-11eb-9943-e47d78064dfc.png)
When we tap the cancel label nothing happens.

![image](https://user-images.githubusercontent.com/10234099/115522288-e0bf9700-a283-11eb-9dc4-f031cda50f6a.png)
After the authorization it simply remains on this view.

**Comment by CodyEngel** [comment]
@mikasR -- it looks like the `returnUrl` is incorrect, to run the sample app you will want to use `com.paypal.checkoutsamples://paypalpay`. Please update the value in the PayPal developer console, let me know if that resolves the issue.

**Comment by mikasR** [comment]
@CodyEngel 
I've tried that, but this is what happens:
![image](https://user-images.githubusercontent.com/10234099/115581130-a247cd80-a2bf-11eb-93ee-6e828e570054.png)

That's why i changed it on the developer dashboard.

**Comment by CodyEngel** [comment]
Hey @mikasR -- can you give it one more try? Sometimes it can take a bit for the new return url to become associated with the application. I tried the sample app using the Client ID you provided and I was redirected successfully, it took ~5 seconds of waiting on redirect screen before control was handed back to the pay sheet.

**Comment by mikasR** [comment]
@CodyEngel correct. It's working now!

Thank you.

**Comment by CodyEngel** [comment]
Thanks @mikasR really happy that solution worked!

Just in case others stumble across this issue the solution was to set the following returnUrl in the developer console: `com.paypal.checkoutsamples://paypalpay`

That returnUrl is required to use the sample application. Sometimes it can take a bit for new returnUrls to propagate through the system, it's usually fairly quick but sometimes it can take up to 3 hours before it's registered.
