### ISSUE TITLE
Button paypal does not show when setup called time second

### ISSUE THREAD

**Issue by tnv1998** [paypal/android-checkout-sdk#50]
The error from your example github

https://github.com/paypal/android-checkout-sdk/blob/main/quickstart-kotlin/src/main/java/com/paypal/checkoutsamples/paymentbutton/PaymentButtonQuickStartActivity.kt

This video: https://drive.google.com/file/d/1KfvUy5U011JMngmXf7-V-_8yH_PgBMfW/view?usp=sharing

**Comment by nvngoc2409** [comment]
@jcnoriega

**Comment by faiz106** [comment]
I was having the same issue until i downlgraded to 0.20 version

   implementation'com.paypal.checkout:android-sdk:0.2.0'

**Comment by A-10ng** [comment]
But when I downlgraded to 0.20 version, all the http requests can not receive response, so strange @faiz106

**Comment by jcnoriega** [comment]
Hi! Thank you so much for reporting. A pull request to fix this has been created and it will be included on the next release next week. 
The bug happens when `PayPalCheckout.setConfig()` is called in the `Application` class. A quick workaround this, is to call `setConfig()` on the same activity that renders the `PaymentButton`.

**Comment by A-10ng** [comment]
Hello, @jcnoriega ，I remove ```setConfig()``` in the ```Application```  and call setConfig() on the same activity that renders the PaymentButton, but it stiil can't work. If I pay the bill, next time I enter the activity and error happens. if not, things go well.

**Comment by jcnoriega** [comment]
Version 0.4.5 is deployed with the fix. Please confirm if issue persists

**Comment by A-10ng** [comment]
Problem solved !

**Comment by jcnoriega** [comment]
resolved, closing issue
