### ISSUE TITLE
lateinit property abManager has not been initialized

### ISSUE THREAD

**Issue by A-10ng** [paypal/android-checkout-sdk#53]
When I start Charles and then start my App, My app crashes. 
When I start my App and then start Charles, everything goes well.
Here is the log：

```
# OkHttp Dispatcher(6338)

kotlin.UninitializedPropertyAccessException

lateinit property abManager has not been initialized

com.paypal.pyplcheckout.services.callbacks.BaseCallback.retryOnError(BaseCallback.kt:78)
com.paypal.pyplcheckout.services.callbacks.BaseCallback.onFailure(BaseCallback.kt:40)
okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:525)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
java.lang.Thread.run(Thread.java:923)
```

**Comment by tdchow** [comment]
@A-10ng - Thanks for reporting this issue. Our team will take a look. 

Are you seeing a similar issue when using the built-in Network Profiler in Android Studio?

**Comment by tdchow** [comment]
@A-10ng - Actually after looking into the issue, it should be resolved in the latest release of the SDK. Can you try testing with version `0.5.0`?

**Comment by A-10ng** [comment]
Problem solved，Thx！ @tdchow
