### ISSUE TITLE
Double-click an entry in the PayPal address list, the APP flashes back

### ISSUE THREAD

**Issue by ZhihaoYang** [paypal/android-checkout-sdk#60]
**Describe the bug**
Double-click an entry in the PayPal address list, the APP flashes back

**To Reproduce**
1. Login paypal
2. Click on 'Shipping address options'
3. Double click any entry of paypal address list.

**Expected behavior**

**Screenshots**

https://user-images.githubusercontent.com/21983345/139200117-91c7b9bb-86f2-4437-a1d9-d1da335441fb.mp4

**Smartphone (please complete the following information):**
 - Android Version: [Android 9.0 API 28]
 - Device: [Samsung Galaxy S9]
 - SDK Version [0.3.1 ~ 0.5.1]

### build.gradle
  `minSdkVersion 23`
  `targetSdkVersion 30`

**Comment by tdchow** [comment]
Hey @ZhihaoYang - Thanks for reporting this issue! I was able to reproduce the crash and have reported it to the team who created the shipping page. Will keep you updated.

**Comment by tdchow** [comment]
@ZhihaoYang - This issue is now fixed in the latest version of the SDK (0.5.2). Could you please pull down the latest version and verify the fix?

**Comment by ZhihaoYang** [comment]
> @ZhihaoYang - This issue is now fixed in the latest version of the SDK (0.5.2). Could you please pull down the latest version and verify the fix?

Version 0.5.2 has been verified, this problem has been fixed, thank you.
