### ISSUE TITLE
Payment hangs up on stage "Pulling up your digital wallet..."

### ISSUE THREAD

**Issue by alexandertechhub** [paypal/android-checkout-sdk#63]
Hello,

I have a question related to the PayPal Native Checkout SDK. I've already tried to find a similar problem here, but didn't find any. Originally we asked this question in the PayPal issue tracker, but they directed us here.

Here is the issue's description:

The first payment attempt brings the full sized login window. Enters login/pass there and press "Log in" button. After that, the bottom panel should be shown in front of the app's window. However, it shows under app's window, please check the screenshot paypal1.png; the app's log for this attempt stored in the file paypal_log.txt.
On each next attempt, login window doesn't show, but bottom panel appears on the screen and the payment process is hanged up on a stage "Pulling up your digital wallet..."; please check the screenshot paypal2.png and the log file paypal_log2.txt. However, this process can be aborted by the device's "Back" button - it brings to screen the exit dialog, screenshot paypal3.png.
Restarting the app doesn't help and payment process finishes with the same result - process hangs on the same stage. If app's data/cache will be cleaned - only then payment process will be started with the login window.

The used device is Samsung SM-G900F Android 6.0.1, API 23. PayPal Native Checkout SDK version 5.0.1.

Could you, please, help with the resolving of this issue? Thank you in advance!

[paypal_log.txt](https://github.com/paypal/android-checkout-sdk/files/7511925/paypal_log.txt)

[paypal_log2.txt](https://github.com/paypal/android-checkout-sdk/files/7511926/paypal_log2.txt)

![paypal1](https://user-images.githubusercontent.com/94047869/141097805-9857bac6-8fb6-4d22-8f73-42ec8c26ed3a.png)
![paypal2](https://user-images.githubusercontent.com/94047869/141097799-7033506d-94f2-421b-b7ef-b0e594587d8a.png)
![paypal3](https://user-images.githubusercontent.com/94047869/141097804-76408d66-8dfd-47ec-81d7-9fc687a09ff7.png)

**Comment by tdchow** [comment]
Hey @alexandertechhub! Thanks for reporting the issue and providing logs and screenshots!

Would you be able to post code snippets of your PayPal integration? (setting config along with invoking the checkout flow or payment button)

Could you also send a screen recording of the first attempt that includes the login process? I'm curious to see how the bottom sheet is displayed behind the app's window.

Thanks!

**Comment by alexandertechhub** [comment]
Hi, here are the requested resources.
Application class code:
```
	@Override
	public void onCreate() {
		super.onCreate();
		
		//.......	
		
		CheckoutConfig config = new CheckoutConfig(
				this ,
				RecorridoCredentials.PAYPAL_CLIENT_ID,
				Environment.SANDBOX,
				String.format("%s://paypalpay", getString(R.string.paypal_returnurl_custom_scheme)),
				CurrencyCode.USD,
				UserAction.PAY_NOW,
				PaymentButtonIntent.CAPTURE,
				new SettingsConfig(true, false)
		);
		PayPalCheckout.setConfig(config);
	}
```
Activity class code:
```
protected void openPayPal(String amount) {
		
	com.paypal.checkout.PayPalCheckout.start(
		new CreateOrder() {
			@Override
			public void create(CreateOrderActions createOrderActions) {
				ArrayList purchaseUnits = new ArrayList<>();
				purchaseUnits.add(
					new PurchaseUnit.Builder()
						.amount(
							new Amount.Builder()
								.currencyCode(CurrencyCode.USD)
								.value(amount)
								.build()
						)
						.build()
				);
				Order order = new Order(
					OrderIntent.CAPTURE,
					new AppContext.Builder()
						.userAction(UserAction.PAY_NOW)
						.build(),
					purchaseUnits,
					ProcessingInstruction.NO_INSTRUCTION
				);
				createOrderActions.create(order,orderId -> { });
			}
		},
		new OnApprove() {
			@Override
			public void onApprove(Approval approval) {
				approval.getOrderActions().capture(new OnCaptureComplete() {
					@Override
					public void onCaptureComplete(CaptureOrderResult result) {
						if (!RELEASE) Log.i(this.getClass().getName(),  String.format("PayPal: CaptureOrderResult: %s", result));

						if ( result instanceof  CaptureOrderResult.Success ) {
							verifyPayment( new Argument( ((CaptureOrderResult.Success)result).getOrderResponse().getId()  ));
						} else {
							CaptureOrderResult.Error error = (CaptureOrderResult.Error)result;
							showDialog( String.format("%s %s", error.getMessage(), error.getReason()), R.string.action_close );
						}
					}
				});
			}
		},
		new OnShippingChange() {
			@Override
			public void onShippingChanged(@NotNull ShippingChangeData shippingChangeData, @NotNull ShippingChangeActions shippingChangeActions) {
				Log.i(this.getClass().getName(), "PayPal: Shipping has been changed: " + shippingChangeData.toString() + " " + shippingChangeActions.toString());
			}
		},
		new OnCancel() {
			@Override
			public void onCancel() {
				Log.i(this.getClass().getName(), "PayPal: Cancelled Checkout.");
			}
		},
		new OnError() {
			@Override
			public void onError(ErrorInfo errorInfo) {
				Log.e(this.getClass().getName(), String.format("PayPal return error: %s", errorInfo.getReason()));
			}
		}
	);
}
```
One thing regarding Screen recording: on 20th second, I switched between opened windows to demonstrate, that app's window has opened bottom panel (the corresponding window marked with red flag).

https://user-images.githubusercontent.com/94047869/141501293-acb247bb-4c14-410d-ae57-c214e606fc12.mp4

 Thank you in advance!

**Comment by alexandertechhub** [comment]
Hello @tdchow! Are there any news regarding the problem? Does the additional info I provided helped you anyhow?

I've seen there appeared a new version of SDK, v0.5.2. I've tested it today, but the issue still persists; nothing were changed so far.

Thank you in advance!

**Comment by ndmunoz10** [comment]
Hey @alexandertechhub, could you please show us your manifest configuration where we can see the configuration you're setting to the Activity that launches our SDK in order to help you further?

Thanks so much for all the info you've provided, it really helps a lot!

**Comment by alexandertechhub** [comment]
Hi, thank you for the response!
Here is a snippet from our manifest file. The PayPal SDK used in one of the fragment of the activity search.SearchAct_:
```
        <activity   
            android:name=".search.SearchAct_"
            android:configChanges="orientation"
            android:screenOrientation="portrait"
            android:windowSoftInputMode="adjustPan|stateHidden"
            tools:ignore="LockedOrientationActivity">
        </activity>
```
and here are definitions of 2 PayPal activities:
```
        <activity
            android:name="com.paypal.openid.RedirectUriReceiverActivity"
            android:excludeFromRecents="true"
            android:theme="@style/PYPLAppTheme">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data
                    android:host="paypalpay"
                    android:scheme="@string/paypal_returnurl_custom_scheme" />
            </intent-filter>
        </activity>
        <activity
            android:name="com.paypal.pyplcheckout.home.view.activities.PYPLInitiateCheckoutActivity"
            android:theme="@style/AppFullScreenTheme">
            <intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data
                    android:host="paypalxo"
                    android:scheme="@string/paypal_returnurl_custom_scheme" />
            </intent-filter>
        </activity>
```
Is it what you are looking for?

**Comment by ndmunoz10** [comment]
@alexandertechhub thanks for your reply, the second snippet is something you are defining in you own manifest file?

**Comment by ndmunoz10** [comment]
@alexandertechhub thanks, will try to debug the issue with all of this information and will get back to you. 

Thank you once more for your patience

**Comment by shafayatb** [comment]
@ndmunoz10 @alexandertechhub Is there any solution to this issue? Having this problem with devices containing marshmellow(Android 6.0). I have tried in other android versions such as android N, O and R. Paypal seems to work on those version but on marshmellow I am facing the same issue as @alexandertechhub posted.

**Comment by alexandertechhub** [comment]
Hi @ndmunoz10 ,
Thank you for the information, first of all! However, I have to say that the behaviour of the PayPal Checkout SDK didn’t changed in v.0.6.0. I’ve made a number of tests based on the example, taken from paypal/android-checkout-sdk (commit fbf4270) [https://github.com/paypal/android-checkout-sdk]; I’ve downloaded it today (March 2nd, 2022). For tests I’ve used the following (real) device: Samsung SM-G900F Android 6.0.1, API 23. I’ve recorded the video of the process and will attach it here, and here will be 2 logs: filtered_log.log - application only (filtered) log and log.log - full log.
Thank you in advance!

https://user-images.githubusercontent.com/94047869/156382285-80e05021-3a10-4045-9592-450f62ab7b6f.mp4
[filtered_log.log](https://github.com/paypal/android-checkout-sdk/files/8170262/filtered_log.log)
[log.log](https://github.com/paypal/android-checkout-sdk/files/8170263/log.log)

**Comment by ndmunoz10** [comment]
Hi @alexandertechhub, version 0.6.0 does not yet include a fix for this issue; you can see what changes are included in each version [here](https://github.com/paypal/android-checkout-sdk/blob/main/CHANGELOG.md). However we can confirm that the next release will have a fix for this issue!

Will keep you posted here.

**Comment by ndmunoz10** [comment]
Hi @alexandertechhub @shafayatb, 0.6.1 version has just been published. It includes a fix for this issue as well as some new fixes and features. Please let us know if you experience the same error after upgrading to the latest version 😄

**Comment by alexandertechhub** [comment]
Hi @ndmunoz10ю All works fine. Thanks!
