### ISSUE TITLE
Unable to receive order notification

### ISSUE THREAD

**Issue by xiaoxiaohaozai** [paypal/android-checkout-sdk#64]
The payment was successfully initiated through the payment button provided by the SDK. It was found that the balance of the sandbox account was reduced, but the order notification could not be found on the developer platform. In the past, it was possible to pay through com.braintreepayments.api:paypal:4.+ Order notification

**Comment by tdchow** [comment]
Hey @xiaoxiaohaozai - Thanks for reporting this issue. It sounds like your Android Checkout integration is working as expected as your transaction was able to pull funds. 

Are you not seeing this transaction in the merchant web dashboard? Could you please share a screenshot of where you're not seeing the order notification?

**Comment by xiaoxiaohaozai** [comment]
> Hey @xiaoxiaohaozai - Thanks for reporting this issue. It sounds like your Android Checkout integration is working as expected as your transaction was able to pull funds.
> 
> Are you not seeing this transaction in the merchant web dashboard? Could you please share a screenshot of where you're not seeing the order notification?

Occasionally, log in to the account and log in to the sandbox platform, and you can see the merchant deductions and records

**Comment by xiaoxiaohaozai** [comment]
> Hey @xiaoxiaohaozai - Thanks for reporting this issue. It sounds like your Android Checkout integration is working as expected as your transaction was able to pull funds.
> 
> Are you not seeing this transaction in the merchant web dashboard? Could you please share a screenshot of where you're not seeing the order notification?
![飞书20211122-102545](https://user-images.githubusercontent.com/14050369/142791972-ec095a35-5311-4231-a5fb-2f2533e5b6af.png)
I can’t see notifications on this platform

![飞书20211122-102549](https://user-images.githubusercontent.com/14050369/142791974-34dc45b2-1b3f-4810-a148-fe97f330e44b.png)
This platform can

**Comment by tdchow** [comment]
Hi @xiaoxiaohaozai - Sorry for the delayed reply! 

This sounds like an issue with the developer portal not showing the correct transactions and not with the Checkout SDK. Could you please reach out to support here: https://developer.paypal.com/docs/support/?

In the meantime, I'll be closing out this issue.
