### ISSUE TITLE
Completion of the PurchaseUnit class

### ISSUE THREAD

**Issue by DevFreeze** [paypal/android-checkout-sdk#65]
It would be really nice, if the PurchaseUnit Object could be extended with the missing parameters `payee` and `payment_instruction`.

**Comment by DevFreeze** [comment]
Alright, nevermind :D was still at 0.2.0

But maybe someone should update the documentation: https://developer.paypal.com/docs/business/native-checkout/android/

**Comment by tdchow** [comment]
Hey @DevFreeze - Thanks for taking another look at this! The code snippet we shared [here](https://developer.paypal.com/docs/business/native-checkout/android/#sample-code-1) only contains the most basic fields to create an order.

Thanks for your feedback! We'll think of ways to better surface these parameters.

**Comment by DevFreeze** [comment]
Hey @tdchow - Thanks for the answer :) 

I was only refering with updating the documentation on this part:

> 3. Add the Native Checkout SDK dependency to the build.gradle file of your app module.
> 
> ```
> dependencies {
>     implementation('com.paypal.checkout:android-sdk:0.2.0')
> }
> ```

Since the code on this section: https://developer.paypal.com/docs/business/native-checkout/android/programmatically-start-sdk/
doesn't work anymore with version 0.2.0

However the addition of the payee parameter already helped me out a lot :D so thanks for your work ;)

**Comment by tdchow** [comment]
Ah! We're really out of date in the dev docs 😅 I'll make sure that this page is updated. Thanks for bringing this to our attention!
