### ISSUE TITLE
com.google.gson.JsonSyntaxException

### ISSUE THREAD

**Issue by lmzliuying** [paypal/android-checkout-sdk#68]
Before you create a new issue, please search for similar issues. It's possible somebody has encountered this bug already. **PLEASE REMOVE THIS LINE TO ACKNOWLEDGE THAT AN ISSUE DOESN'T ALREADY EXIST FOR THIS BUG**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Android Version: [e.g. API 30]
 - Device: [e.g. Emulator or One Plus 9]
 - Browser [e.g. chrome, safari] <- only applicable for app switches or fallback situations
 - SDK Version [e.g. 0.1.0]
![1636946597(1)](https://user-images.githubusercontent.com/94339070/141721155-a192bf75-22b3-4a54-9660-6ed32d62edf3.jpg)

**Additional context**
![1636946633(1)](https://user-images.githubusercontent.com/94339070/141721170-71a098a8-f535-4289-8433-818ebe817d19.jpg)
<img width="576" alt="1636946536(1)" src="https://user-images.githubusercontent.com/94339070/141721202-890e8a1f-7721-49e0-9e2b-580693b1ccef.png">

**Comment by tdchow** [comment]
Hey @lmzliuying - Which version of the SDK are you using? Can you try pulling in the latest version of the Checkout SDK (version 0.5.2)? There was some error handling that was recently added.

**Comment by lmzliuying** [comment]
> 嘿@lmzliuying - 您使用的是哪个版本的 SDK？您可以尝试使用最新版本的 Checkout SDK（版本 0.5.2）吗？最近添加了一些错误处理。

是的，我更新到最新版本的SDK，问题已经解决。谢谢！

**Comment by tdchow** [comment]
@lmzliuying - Glad that your issue is resolved! No problem!
