### ISSUE TITLE
Paypal Retunr Url

### ISSUE THREAD

**Issue by nafiskabbo** [paypal/android-checkout-sdk#7]
![Screenshot_2021-04-26 Edit applications - PayPal Developer(1)](https://user-images.githubusercontent.com/69830273/116063998-69d13680-a6a7-11eb-9fe6-2ae69a1f08fe.png)

**My application id is "soft.agency.kbt.com.i69.stage". In Paypal Developer, when I try to add this in return url with "://paypalpay". it always says "Oauth invalid return URL".** 

But when I remove the number from my application id, it works but the problem is I cannot change my application id as it is already published in the google playstore. please tell me what to do?

**Comment by CodyEngel** [comment]
Hey @nafiskabbo -- thank you for reporting this bug. At first glance it looks like numerics are throwing off the return url check. I'll make sure to get this issue to appropriate team so that it can be addressed. I'll will keep you updated and will let you know once we have an ETA for this issue.

**Comment by nafiskabbo** [comment]
@CodyEngel  thanks a lot. But by when this bug can be solved?
**Thanks!**

**Comment by CodyEngel** [comment]
@nafiskabbo -- I will provide you with an ETA once I have one. My team does not manage the developer console so I'm currently working with that team.

Short-term if you are looking to get familiar with the SDK I'd suggest checking out our quick start demos available in this repository.

**Comment by nafiskabbo** [comment]
@CodyEngel Actually, I have tried the sdk and explored it with one sample apk. I am impressed with its features. But I need to implement it for a client. Client was pressuring me. That's why i asked you. Thanks!

**Comment by CodyEngel** [comment]
Hey @nafiskabbo -- I don't have an ETA yet but the developer portal team is aware of the issue and I can see them discussing this internally. As soon as I have more information I will share it with you. Thank you for your patience and bringing this bug to our attention, it's very much appreciated 😌

**Comment by nafiskabbo** [comment]
@CodyEngel  any update bro? By when this can be fixed? Can you please tell me an approx time?

**Comment by CodyEngel** [comment]
Hey @nafiskabbo -- the team working to resolve this aren't able to provide an ETA. However they informed me that you can reach out to [PayPal Support](https://www.paypal-support.com/) and an agent should be able to manually add your Return URL for the time being.

Once the fix has been deployed I'll go ahead and update the status of this ticket.

**Comment by nafiskabbo** [comment]
I have submitted a request to the Paypal support team.

 **My Case Number; 08158693**

Can you tell them to please check it? Please try to resolve it!

**Comment by nafiskabbo** [comment]
Hey  @CodyEngel 

![Screenshot_2021-04-30 Return Url Fix   Case # 08158693    ref _00D30LaY _5002E1leLbO ref   - kabboandreigns gmail com - Gmail](https://user-images.githubusercontent.com/69830273/116618865-77b1e080-a961-11eb-88fe-0b69f028342a.png)

Response of PayPal customer care. I have written something and they have replied to me the totally wrong answer. Please do something.

**Comment by CodyEngel** [comment]
Hey @nafiskabbo -- support should have reached back out to get additional details from you about your sandbox account so that they can make that change.

**Comment by nafiskabbo** [comment]
Hey @CodyEngel 
 Will the bug of the Return URL be resolved within 2 to 3 days? As We need to make it for Paypal Production Mode.

**Comment by nafiskabbo** [comment]
Hey @CodyEngel 
It's been almost 1 week. Any possibility of the bug fixing quickly. Please respond.

**Comment by CodyEngel** [comment]
@nafiskabbo -- I haven't received any updates from the team working to resolve this bug. I'll see what can be done to expedite this work.

**Comment by nafiskabbo** [comment]
@CodyEngel 
Thanks for replying. I was thinking that fixing the Pattern of a Return Url is not a big task that can take a week. I was wondering if they were working on it or not. As my client is telling me to finish soon, but without it, I cannot finish the integration of Paypal.

**Comment by mstuart** [comment]
Hi @nafiskabbo, do you mind sharing your client-id? It's a public credential, so it's safe to share here. Please don't share your secret though :)

**Comment by nafiskabbo** [comment]
@CodyEngel @mstuart 
Ok I am writing My Sandbox and Live Both Client Ids with my required return url.
* Sandbox Client Id = "AXG6q4YxIzaHkhHu0vlEk1QjYp-tHvMP_JhUjsCehtqZeIZsCs-dNvWxMzFF-KvLesBXYNk4-5gp0_ib"
* Production (Live) Mode Client Id = "AQCdEBLfbKiVI0JrFrJDubigxC4O5YD78R1WU5xxkgBl69pmNoZs5NY2zIQf_SKTFWQJb_AAEJLF5j2Q"
* Return url = "soft.agency.kbt.com.i69.stage://paypalpay"

And please leave a comment here when done adding the return url.
Thanks!

**Comment by mstuart** [comment]
Hi @nafiskabbo, can you try again? We made a change on our end.

**Comment by nafiskabbo** [comment]
Hey @CodyEngel ,
It is now working on the Sandbox mode. Now the client has submitted for Live Production Mode Request. Hoping while editing the scopes, the return url won't be invalid at that time!

**Comment by CodyEngel** [comment]
Hey @nafiskabbo -- the changes have been pushed so you should be able to use numeric values in the return url now.

**Comment by nafiskabbo** [comment]
@CodyEngel 
Thanks for it. I have a question that my client is facing in Live Production Mode but perfectly working in Sandbox mode.
See attached image please and if you can give me any solution.

![Screenshot_20210508-023910_Chrome](https://user-images.githubusercontent.com/69830273/118507457-10ad6d80-b750-11eb-8824-17f76059a8bc.jpg)

**Comment by CodyEngel** [comment]
Hey @nafiskabbo happy to hear the return url is working for production. That screen looks like a web fallback experience which is how the SDK handles flows that are not currently supported with Native. It looks like that card cannot be verified by the issuer, [I found this help article which could help with solving that problem](https://www.paypal-community.com/t5/Archive/quot-This-card-cannot-be-used-for-this-transaction-quot/td-p/169036). If it doesn't, I'd recommend reaching out to support as they'd be able to help resolve that issue.

**Comment by nafiskabbo** [comment]
@CodyEngel 
bro my client is always getting this error. As you said to contact Paypal Support team, I contacted them and they said to try with one of the relatives or other person's paypal account. We tried that. But We are having always the same error in PayPal Live Mode. Images Attached. Please help me.  It's happening always

![Screenshot_20210526-214710_AnyDesk](https://user-images.githubusercontent.com/69830273/119717447-20336180-be88-11eb-9636-3a6ba551a4ff.jpg)
![Screenshot_20210526-215007_AnyDesk](https://user-images.githubusercontent.com/69830273/119717452-21648e80-be88-11eb-955c-b36018d0e844.jpg)
![Screenshot_20210526-214654_AnyDesk](https://user-images.githubusercontent.com/69830273/119717435-1dd10780-be88-11eb-8f3f-aeb33e5da2f8.jpg)

**Comment by nafiskabbo** [comment]
This card can't be used for this type of transaction. Please help!
