### ISSUE TITLE
Do we need any Partner Account to cut platform fee

### ISSUE THREAD

**Issue by microcian** [paypal/android-checkout-sdk#73]
we've requirement to cut our platform fee from user, and invoice fee pay to the payee, so I don't know business account is enough for this purpose or do we need any other account type or setting to do it. help me if anyone dealing with platform fee

**Comment by tdchow** [comment]
Hey @microcian - Currently the Native Checkout SDK does not support multi-seller payments.

**Comment by microcian** [comment]
> Hey @microcian - Currently the Native Checkout SDK does not support multi-seller payments.

Thanks for the response.
If I use server end functuonality using v2sanbox API's , so I cam achieve multi seller payments?

**Comment by tdchow** [comment]
No worries! Unfortunately, multi-seller payments are still not supported even with using server-side order create.

**Comment by microcian** [comment]
1. So there is no way to achieve multi-seller payments.right?
2. My requirement was just to pay some platform fee to the (owner of application/service provider) and rest amount pay to the vendor, how may I implement?

**Comment by tdchow** [comment]
Yep, that's correct. There currently isn't any support for multi-seller payments in the Checkout SDK.
