### ISSUE TITLE
Shipping methods have a weird behaviour inside SDK

### ISSUE THREAD

**Issue by mauro-poq** [paypal/android-checkout-sdk#75]
Hey, as part of my use case I need to allow the user to select the shipping method he wants, when I'm creating the order I'm sending the shipping option inside the `PurchaseUnit`, however when the SDK starts it doesn't show the options directly to the user, to be able to select the shipping method I need to add/edit my shipping address, so I'm redirected to a WebView which also have a weird user flow.
I'm still working on a Spike to understand how the SDK works, here is the code I use to start the SDK:
```
PayPalCheckout.start(
            CreateOrder {
                val order = Order(
                    intent = OrderIntent.AUTHORIZE,
                    appContext = AppContext(
                        userAction = UserAction.PAY_NOW,
                        shippingPreference = ShippingPreference.GET_FROM_FILE
                    ),
                    processingInstruction = ProcessingInstruction.ORDER_SAVED_EXPLICITLY,
                    purchaseUnitList = listOf(
                        PurchaseUnit(
                            referenceId = "1",
                            description = "Description",
                            invoiceId = "Invoice 123456",
                            customId = "CustomId 123456",
                            softDescriptor = "Soft Descriptor",
                            shipping = Shipping(
                                options = listOf(
                                    Options(
                                        id = "Opt1",
                                        selected = true,
                                        label = "Free Shipping",
                                        type = ShippingType.SHIPPING,
                                        amount = UnitAmount(
                                            currencyCode = CurrencyCode.GBP,
                                            value = "0.00"
                                        )
                                    ),
                                    Options(
                                        id = "Opt2",
                                        selected = false,
                                        label = "Standard Shipping",
                                        type = ShippingType.SHIPPING,
                                        amount = UnitAmount(
                                            currencyCode = CurrencyCode.GBP,
                                            value = "3.00"
                                        )
                                    ),
                                    Options(
                                        id = "Opt3",
                                        selected = false,
                                        label = "Expensive Shipping",
                                        type = ShippingType.SHIPPING,
                                        amount = UnitAmount(
                                            currencyCode = CurrencyCode.GBP,
                                            value = "10.00"
                                        )
                                    )
                                )
                            ),
                            amount = Amount(
                                currencyCode = CurrencyCode.GBP,
                                value = "10.00"
                            )
                        )
                    )
                )
                it.create(order)
            },
            OnApprove {approval ->
                approval.orderActions.capture { captureOrderResult ->
                    Log.e(TAG, "Order successfully captured: $captureOrderResult")
                }
            },
            OnShippingChange { shippingChangeData, shippingChangeActions ->
                Log.e(TAG, "startPayPal: OnShippingChange")
            },
            OnCancel {
                Log.e(TAG, "startPayPal: OnCancel")
            },
            OnError {
                Log.e(TAG, "startPayPal: OnError: ${it.reason}", it.error)
            }
        )
```
Here is a video of how the user flow is showing to me:

https://user-images.githubusercontent.com/59827478/148385009-f9587562-2be2-49d8-9de8-3dd17d099147.mp4

As you guys can see above, there is some weird behavior regarding the price that will be charged from the user and it's really complicated to see achieve the Shipping Options section and to change it, so here are some questions:
1 - Is this Shipping Methods selection production ready?
2 - Is there any config I should change in order to make this selection easier for the user?
3 - At the beginning of the video we can see that there are some values for "Postage and packaging", is there a way to set this value in the order creation (question 4 is related to this too)?
4 - I imagine this "Postage and packaging" should be updated when I receive a call on `OnShippingChange`, as it's explained in this [document](https://developer.paypal.com/sdk/in-app/android/update-shipping/), however, the method with my log is never called so I'm not able to change it (I guess this is a Bug), how can I change the initialization in order to receive the call?

Thanks,
Mauro Cesar Calegari

**Comment by tdchow** [comment]
Hey @mauro-poq - Sorry for the delay!

Right now the shipping feature built into the SDK only handles changing shipping methods and selecting a different shipping address (selecting an already existing address). The SDK does not handle adding or editing addresses. Opening the webview is expected behavior as we do not have this feature built out natively. With that said, we should be releasing a new version that has adding a shipping address natively soon!

> 1 - Is this Shipping Methods selection production ready?

Yes, the `OnShippingChange` callback is production-ready.

> 2 - Is there any config I should change in order to make this selection easier for the user?

Passing in the different shipping options should be enough to show a selection within the paysheet. I'm also seeing some weird behavior where the paysheet should include a shipping options view. I'll spend some time looking into this issue.

> 3 - At the beginning of the video we can see that there are some values for "Postage and packaging", is there a way to set this value in the order creation (question 4 is related to this too)?

You can set the `BreakDown` object within `Amount`. Here's an example:
```kotlin
  amount = Amount(
      currencyCode = CurrencyCode.GBP,
      breakdown = BreakDown(
          shipping = UnitAmount(
              currencyCode = CurrencyCode.GBP,
              value = "3.00"
          ),
          handling = UnitAmount(
              currencyCode = CurrencyCode.GBP,
              value = "2.00"
          ),
          itemTotal = UnitAmount(
              currencyCode = CurrencyCode.GBP,
              value = "10.00"
          )
      ),
      value = "15.00"
  )
```

> 4 - I imagine this "Postage and packaging" should be updated when I receive a call on OnShippingChange, as it's explained in this document, however, the method with my log is never called so I'm not able to change it (I guess this is a Bug), how can I change the initialization in order to receive the call?

I'm also seeing this behavior where the callback is not being invoked. I'll be looking into this issue as well.

**Comment by mauro-poq** [comment]
Hey @tdchow, tks for the reply!
Nice I will wait for the next release, however, this is a key feature for me, so sorry to ask you that but do you have an idea of when it will be available or a Snapshot with the changes?

**Comment by tdchow** [comment]
@mauro-poq - Not a problem! Unfortunately, I don't have an estimate for you right now as we're pretty backed. But will keep you updated here in the thread.

**Comment by mauro-poq** [comment]
@tdchow awesome, thanks!

**Comment by mauro-poq** [comment]
Hey @tdchow , looks like ins the class `DebugConfigManager` you have the method `isShippingCallbackEnabled` that is always returning `false`. If I include this `DebugConfigManager.getInstance().setShippingCallbackEnabled(true)` on my side it shows the shipping method selection and the callback works.
I don't know if this is a bug or something expected, if it's something expected can you include this info in the documentation please?
I will use this flag while we don't have a new version.

**Comment by tdchow** [comment]
@mauro-poq - Thanks for digging into this issue! This is definitely not expected behavior. A fix is currently underway and will be included in the next release.

We don't intend for integrations to access the `DebugConfigManager` class, but in this case, it should unblock you for the time being.

Thanks again for looking into the issue!

**Comment by mauro-poq** [comment]
No problem! Thanks.

**Comment by tdchow** [comment]
Hey @mauro-poq! Version 0.5.4 was just released which should fix the shipping callback issue!

**Comment by mauro-poq** [comment]
Hey @tdchow amazing, I will check! Thanks!

**Comment by mauro-poq** [comment]
Version 0.5.4 fixed this, closing the issue
