### ISSUE TITLE
OnShippingChange callback never invoked

### ISSUE THREAD

**Issue by mauro-poq** [paypal/android-checkout-sdk#81]
**Describe the bug**
The OnShippingChange callback is never invoked.

**To Reproduce**
1. Create a sample app as described in https://developer.paypal.com/sdk/in-app/android/
2. Include the callback as described in https://developer.paypal.com/sdk/in-app/android/update-shipping/
3. Run the app and add/change user shipping address.
4. Callback is not invoked

**Expected behavior**
The callback should be invoked

**Smartphone (please complete the following information):**
 - Android Version: API 31
 - Device: Google Pixel 4
 - SDK Version: 0.5.2

**Comment by tdchow** [comment]
Hey @mauro-poq! It looks like the other issue you opened (https://github.com/paypal/android-checkout-sdk/issues/75) captures this bug. I'll be closing this one as a duplicate.
