### ISSUE TITLE
Is Billing Address in the Order Response?

### ISSUE THREAD

**Issue by mauro-poq** [paypal/android-checkout-sdk#82]
Is there a way to retrieve the payer Billing Address?

In the iOS documentation, they have an Address object inside the Payer object which is referred as the user Billing Address:
<img width="815" alt="image" src="https://user-images.githubusercontent.com/59827478/150966660-8aa42d15-b3d0-455a-8221-acea701f295c.png">

I was not able to find an explicit way to retrieve the payer Billing Address, is it available? 
If not, is it possible to include it?

**Comment by tdchow** [comment]
Hi @mauro-poq - We recently added the billing address to the `Cart` object in the `OnApprove` callback: 

```kotlin
package com.paypal.pyplcheckout.pojo

data class Cart(
    val cartId: String? = null,
    val intent: String? = null,
    val billingType: BillingType? = null,
    val paymentId: String? = null,
    val billingToken: String? = null,
    val items: List<Item>? = null,
    val amounts: Amounts? = null,
    val description: String? = null,
    val cancelUrl: CancelUrl? = null,
    val returnUrl: ReturnUrl? = null,
    val total: Total? = null,
    val shippingMethods: List<ShippingMethods>? = null,
    val shippingAddress: CartAddress? = null,
    val billingAddress: CartAddress? = null
)
```

You'll need to be using the latest version of the Checkout SDK: version 0.5.4.

**Comment by mauro-poq** [comment]
Hey @tdchow amazing, I will take a look! Thanks

**Comment by mauro-poq** [comment]
Hey @tdchow the Billing Address is present now, however, the `billingAddress.firstName` and `billingAddress.lastName` are not being returned (both are returned for the `shippingAddress`), at least I'm receiving `null`, is there a flag or something to retrieve those fields?

**Comment by tdchow** [comment]
Hi @mauro-poq - Sorry for the delay. I just got confirmation that a request needs to be made for the billing address to be returned. Can you reach out to technical support here to ask for access to this information?

 https://www.paypal-support.com/s/?language=en_US -> “Contact Us”

**Comment by mauro-poq** [comment]
Hey @tdchow, I already have the billing address because this config was done before by the iOS Dev, however, I'm not receiving the fields `firstName` and `lastName` for the Billing Address, fields that are present in the Shipping Address.

**Comment by tdchow** [comment]
@mauro-poq - Apologies! Let me check on this for you. Are you able to see `firstName` and `lastName` returned in the iOS SDK?

**Comment by mauro-poq** [comment]
@tdchow - No problem, well the iOS dev in my company said that the values are present, but looking at the iOS code, I can see that if the fields in the Billing Address are not present he is getting the Payer name instead, so I'm not sure if iOS is receiving it or not.

**Comment by tdchow** [comment]
Hi @mauro-poq - Sorry for the delay! Please comment here if you still are having issues or still have a use case for the first name and last name to be returned. Thanks!

**Comment by mauro-poq** [comment]
Hey, @tdchow - I just tested using version 0.8.8 and I still don't receive the First and Last name for Billing Address:
![image](https://user-images.githubusercontent.com/59827478/225390454-8b07c7cd-5a7e-411e-bf8a-927ffac72ea0.png)
The object is `com.paypal.pyplcheckout.pojo.CartAddress` returned in `com.paypal.checkout.approve.ApprovalData -> com.paypal.pyplcheckout.pojo.Cart`
I still have the use case.

**Comment by tdchow** [comment]
Thanks for verifying. I'll reopen this issue and make sure our team tracks this.

**Comment by mauro-poq** [comment]
Hey @tdchow how are you?
Did you guys find something related to this?
Also, we are having another problem with some users who are directed to the PayPal web checkout experience, for some reason the object `ApprovalData.Cart` is returned as `null` and this is preventing us from getting the necessary addresses. 
For users who are directed to the PayPal Native experience, it works fine. 
Do you know if something is necessary in order to have this info?

By the way, we have updated to the latest version 1.0.0.

**Comment by MaxHastingsPP** [comment]
Hi @mauro-poq 

Can you use the Android network inspector and find the GraphQL request GET_USER_AND_CHECKOUT_SESSION that is being made. Look at the response and double check if Cart is coming back as null. And then in the headers of the response look for a PayPal debug id and post that here.

We can then pass this debug id along to our backend teams to further triage the issue.

Thank you.

**Comment by MaxHastingsPP** [comment]
@mauro-poq 

Interesting that you do not see a `GET_USER_AND_CHECKOUT_SESSION` GraphQL call being made.

Can you post a video or screenshots of what your checkout flow currently looks like when testing? You should be seeing a screen like this during checkout.

<img width="411" alt="Screenshot 2023-10-17 at 2 26 27 PM" src="https://github.com/paypal/android-checkout-sdk/assets/128730898/c7d2f95b-8291-4ed9-946c-40679741b02f">

Perhaps you are falling back to a web browser checkout experience instead?

**Comment by mauro-poq** [comment]
@MaxHastingsPP 

For this specific user, I'm seeing this screen:
![image](https://github.com/paypal/android-checkout-sdk/assets/59827478/449c7b04-bb20-45fa-a544-c0e01dac6158)

For other users I see the screen you sent, everything works fine with that users.

**Comment by MaxHastingsPP** [comment]
@mauro-poq 

Yeah in that case the user is falling back to a web view checkout experience instead of a native screen like I showed above. In this case you would not get Cart data.

**Comment by MaxHastingsPP** [comment]
@mauro-poq You would need to make a get request against the orders or payments api to get buyer information associated using their EC token.

You can not force native checkout experience.

**Comment by mauro-poq** [comment]
@MaxHastingsPP is there any documentation explaining how to do these calls or can you provide any guidance?

**Comment by MaxHastingsPP** [comment]
@mauro-poq https://developer.paypal.com/api/rest/

**Comment by mauro-poq** [comment]
@MaxHastingsPP thanks I will check with our BE devs!
