### ISSUE TITLE
SDK Size

### ISSUE THREAD

**Issue by Bhullnatik** [paypal/android-checkout-sdk#83]
Hello,

We recently integrated the PayPal SDK in our application, and while the integration was very pleasant we found that the SDK was adding almost up to 20MB to our APK size, almost doubling it which seems very heavy.

|   | APK Size | Minified |
| ------------- | ------------- | ------------- |
| Without PayPal SDK  | 34.5 MB  | 29 MB |
| With  | 54.2 MB  | 46.6 MB |

Mostly all of it comes from an increase in dex files (12.5 MB) and resource files (2 MB).

Is this something looked into? We are of course interested in having PayPal as a payment method but that seems like a high price to pay.

**Comment by tdchow** [comment]
Hey @Bhullnatik - Thanks for reaching out! The inclusion of the PayPal Checkout SDK shouldn't be adding anywhere close to 20 MB to your APK size. 

I just created an empty sample project and added version 0.5.4 of the Checkout SDK. Here are the numbers that I'm seeing:

- APK size increase: 5 MB
- Download size increase: 4.6 MB

### With the PayPal Checkout SDK
![dex size with paypal sdk](https://user-images.githubusercontent.com/5005216/151866229-08b86c6d-1743-4caa-84b0-71465c6be9e0.png)

### Empty Project
![dex size empty project](https://user-images.githubusercontent.com/5005216/151866321-7858abc3-36f5-4cf8-ac36-6489104b4ea6.png)

### Few follow up questions:
- Would you be able to provide screenshots of the APK Analyzer tool, with and without including the SDK?
- Which version of the SDK are you building your app with?

**Comment by Bhullnatik** [comment]
Hello @tdchow, thank you for your answer.

So you're totally right. For some reason, the size of some native libraries we were using jumped to 20MB more when we added the PayPal SDK but the APK Analyzer tool was showing the difference in dex files rather than the native libs while analyzing them separately showed where the problem was.

After fixing this issue, everything went back to normal and getting numbers close to yours.

Sorry for the disturbance and thank you for the help!
