### ISSUE TITLE
Update the Upgrade Guide!

### ISSUE THREAD

**Issue by picassos-developers** [paypal/android-checkout-sdk#92]
Upgrade guide needs to be updated for v.0.6.0. https://developer.paypal.com/sdk/in-app/android/upgrade/

**Comment by abedsh** [comment]
@picassos-developers now that it's mandatory to Initialize the Native Checkout SDK in oncreate method of the App, the Client Paypal ID needs to be stored on the app. Is that safe to do ?

**Comment by tdchow** [comment]
Hey @picassos-developers - That upgrade page actually only includes changes for version 0.6.0. This is the only version that has deprecated functions and breaking changes. But I see how it's confusing. Will see if we can update this to make it clearer!

@abedsh - Yep, you'd be safe having your client ID in your app's source code. However, I would recommend obfuscating your app for your release build!

Closing this issue out. We'll look at making some updates to the upgrade guide!
