### ISSUE TITLE
PayPal not proceeding the login page

### ISSUE THREAD

**Issue by dscoder421** [paypal/android-checkout-sdk#97]
**Describe the bug**
When I click the customized PayPal button (started programmatically), it opens chrome, and when I add the sandbox credentials it dosen't proceed the email login

**To Reproduce**
1. Create a custom button and start the SDK programmatically or use the PayPal button
2. Click on the button
3. Enter the sandbox credentials
4. It won't proceed after entering the email

**Expected behavior**
Should proceed to password page and return back to the app for further payment

**Screenshots**

<img src="https://user-images.githubusercontent.com/50439943/159106464-a3435040-a6d5-412b-9c6b-28be7263a011.png" width="300px" />
<img src="https://user-images.githubusercontent.com/50439943/159106443-c50cd3c7-d090-4d7c-b443-e560b7444ad2.png" width="300px" />

**Smartphone (please complete the following information):**
 - Android Version: API 27
 - Device: OPPO A5
 - Browser: Chrome
 - SDK Version: 0.6.1

**Additional context**
I have tried using the SDK's button and also used it programmatically and both give the same error

**Comment by dscoder421** [comment]
And one more thing, The problem is Chrome blocks third-party cookies which doesn't allow PayPal to proceed after the main login page. If I disable the **Block third-party cookies** it works great.

It would be great if the team fixes this issue from the SDK

**Comment by tdchow** [comment]
Hey @dscoder421 - Thanks for reporting this issue.

Would you be able to provide a screenshot of the error screen you're seeing on the email prompt webpage? Or would you be able to share a screen recording of the entire flow?

**Comment by dscoder421** [comment]
Hi Tim Chow,

Please find the screen recording (it goes blank when I type my password). Please watch till end

https://user-images.githubusercontent.com/50439943/159292196-2edfc122-aee3-4e38-9230-400dbebc91e7.mp4

**Comment by tdchow** [comment]
hi @dscoder421 - Sorry for the delay! Are you still seeing issues with this auth flow? I'll be closing this issue for now, but if you still need support on this please comment here and we can reopen the issue.

We also have a native OTP feature in the later versions of the SDK which would bypass the need for web authentication.
